### ISSUE TITLE
Halo Infinite crashes on startup

### ISSUE THREAD

**Issue by salehif** [winsiderss/systeminformer#1037]
Hi

while trying to play Halo Infinite game, it was freeze every time after intro

I discovered that game anti-cheat system defined process hacker as hacking tool

after closing the process hacker, the game start works fine

**Comment by dmex** [comment]
> freeze every time after intro

Halo is calling the EnumWindows API and crashing with a null reference exception when trying to parse the PH window title then it crashes a second time with a stack overflow after trying to query the filename.

I've lodged a ticket with 343 since both of those crashes are caused by faulty programming in their binary... If you've paid for this product then I would suggest refunding their product until after they've fixed these crashes so you don't suffer with any unintended side effects caused by their crashes.

**Comment by dmex** [comment]
![image](https://user-images.githubusercontent.com/1306177/144246295-861a6c39-1c14-4084-8656-4b8372e730b8.png)

**Comment by dmex** [comment]
https://aka.ms/halosupport

**Comment by dmex** [comment]
Here's a workaround until they fix Halo.

1) Enable the `Show Advanced options` checkbox on the options window.
2) Select the `Advanced` tab on the options window.
3) Search for `EnableWindowText` and change the setting from 1 to 0 - this will disable the window icons and text.
4) Exit the application.
5) Rename the `processhacker.exe` binary to whatever, can be anything.

This will prevent Halo's built-in spyware from crashing the game.

**Comment by DankuwOs** [comment]
This fixed it for me, although I'm 90% sure that doing this got me banned from Destiny 2. F

**Comment by Masamune3210** [comment]
If you got banned for using something benign, then their DRM is at fault, not you.

**Comment by dmex** [comment]
> This fixed it for me, 

This was a fix years ago for bitcoin miner malware closing the window... never imagined it would be needed to workaround a major AAA game bug 🤔

> although I'm 90% sure that doing this got me banned from Destiny 2. 

Look at the top 1000 games: https://steamdb.info/graph/

None of these other games or companies in the top 1000 are banning anyone for PH or saying it's a cheat... It doesn't get much more plainly obvious Bungie isn't doing the right thing by anyone here.

**Comment by dmex** [comment]
This issue is no longer applicable.
