### ISSUE TITLE
ProcessHacker v3 `DisplayVersion` should display the actual build version instead of `3.x`

### ISSUE THREAD

**Issue by itsmeboy0** [winsiderss/systeminformer#1262]
### Description of the feature, modification, idea or suggestion

For example, what would display here should be `3.0.4953` instead of `3.x`.
![image](https://user-images.githubusercontent.com/75471378/173514020-2c60511a-c408-4fd0-ba3d-aff0f705c9dd.png)

**Comment by TheEragon** [comment]
But why? You will have only one version installed anyway

**Comment by itsmeboy0** [comment]
Two different build versions are two different builds. Winget also gets the version info from here, so it would allow for Process Hacker v3 to be added in Winget; the other problem that would need to be resolved would be #759.

**Comment by jxy-s** [comment]
This is due to the display version here: https://github.com/winsiderss/systeminformer/blob/master/tools/CustomSetupTool/util.c#L53

This is likely to be resolved as we approach an official 3.x release. For the time being, for the nightly, this is unlikely to change. I'm unsure if the upgrade path handles changing the display version when we do change this to display the actual version that path will need to update too.

**Comment by dmex** [comment]
I'll wrap this into #759

**Comment by itsmeboy0** [comment]
Um, they aren't related?

**Comment by dmex** [comment]
@itsmeboy0 

They'll both be addressed in the same commit.
