### ISSUE TITLE
[Feature Request]: Thread tokens: request to show a count of thread that have a token 

### ISSUE THREAD

**Issue by AltF5** [winsiderss/systeminformer#1275]
### Description of the feature, modification, idea or suggestion

Threads can have tokens to impersonate and grant a process access to higher privileged resources like System integrity level, NT Service\TrustedInstaller group, and any number of privileges in order to arbitrarily spawn tokens & processes with NtCreateToken.

This is exposed with the “Impersonation” column in a process’s thread list (thrdlst.c). Threads that have tokens can be right clicked to vids their Token which calls out what this sneaky thing is doing.

To locate processes with threads that have tokens (can be opened successfully with OpenThreadToken for example) it requires clicking through EVERY process on the box switching to the Threads tab, and checking for a “Yes” in the Impersonation column. There should be an easier way. If at least an indicator column  in the process tree view of a “Yes” for a process that has 1 to [n] number of threads whom is impersonating. This should be refreshed if the thread is no longer (a weakness in my implementation via Pull Request; amount functional design issues that I need more of an expert to help assist with) 

See right-most column here
![1](https://user-images.githubusercontent.com/1288507/174197018-d8d24021-0f46-4610-abae-c56eb1cfa05b.png)

### Proposed implementation details (optional)

Attempted in this PR here (among 4 other columns), and did work, **but with some design issues perhaps we can discuss for a future pull request implementation**

# https://github.com/winsiderss/systeminformer/pull/1272

See: 
- PHPRTLC_THREADTOKENCOUNT
- BEGIN_SORT_FUNCTION(ThreadTokenCount)
- PhpUpdateProcessNodeThreadTokenCount
- Thread storage attempt in procprov.c - if (threadList && Process->Threads[i].ClientId.UniqueThread)

**Comment by jxy-s** [comment]
I think your original implementation here is close. However, I think we should bite the bullet and actually try to track which threads are associate with a process item. We may have a transient TID associated with a process that isn't during a refresh/update. But I'd rather have that than leaking a list of TIDs.

Please give me some time I want to look into an appropriate solution to support your enhancement proposal.

**Comment by diversenok** [comment]
I would also suggest changing the logic behind determining if a thread has a token. The current implementation doesn't account for inaccessible tokens (due to a non-permissive security descriptor or an anonymous-level impersonation). You should check for `STATUS_NO_TOKEN` instead; see the code from the thread tab provider:

https://github.com/winsiderss/systeminformer/blob/c6844b50e3a4375eee94157f24de689d341de6ba/SystemInformer/thrdlist.c#L1176-L1213

**Comment by jxy-s** [comment]
@AltF5 I had a brief look into what it would take to do this with the current infrastructure we have. It certainly _would_ be possible, although @dmex and I both agree it is way unnecessary/overkill _just_ to display the number of threads that are impersonating in the process list.

There is a significant cost to tracking all threads associated with all processes on the system and doing it _just_ to show a count of threads that are currently impersonating in the process list is way overkill. In order to achieve this correctly we must hold a handle open to every thread on the system. And then check for thread expiring. Without this the system _will_ get into a TID reuse problem. Using all those system resources _just_ to display this small bit of information in unacceptable overhead. We simple don't have enough justification/need for doing all that tracking.

Furthermore, the impersonating threads are going to change frequently. Especially between updates, under almost all circumstances (with the exception of a few outliers) impersonation will happen then the thread will immediately revert to itself. With that in mind a count of the number of impersonating thread really doesn't make much sense.

Perhaps, in the future, if we have more need in the project to track threads items associated with a process item something like this _could_ be considered. But at this time our recommendation is for you to maintain this in your own builds. It's simply not something we can accept in the main repo at this time.

**Comment by AltF5** [comment]
I truly appreciate the consideration all. While I’m disappointed with this conclusion, I’m OK to accept that the answer is no given then rationale. If you all have suggestions to improve my implementation (even if not perfect or worthy for in the main repo) before this gets left in the dust, don’t hesitate to drop some more tips. Thank you all. Godspeed :-)

**Comment by AltF5** [comment]
> I would also suggest changing the logic behind determining if a thread has a token. The current implementation doesn't account for inaccessible tokens (due to a non-permissive security descriptor or an anonymous-level impersonation). You should check for `STATUS_NO_TOKEN` instead; see the code from the thread tab provider:
> 
> https://github.com/winsiderss/systeminformer/blob/c6844b50e3a4375eee94157f24de689d341de6ba/SystemInformer/thrdlist.c#L1176-L1213

Thank you @diversenok … maybe I’ll implement this and discuss with you on twitter if I have any question (I’m winlogon0 as we have DMed frequently)
