### ISSUE TITLE
Feature Request: Record data written by process.

### ISSUE THREAD

**Issue by darkworks** [winsiderss/systeminformer#1368]
### Description of the feature, modification, idea or suggestion

I request that please add feature so that in Disk tab we have column where it shows total average data written by process in the current opened session by process hacker. 

something like this.
![image](https://user-images.githubusercontent.com/12841788/188375147-0442db36-ce34-45b9-b612-0cbd0730d1ff.png)

it will be very useful feature to track down faulty process. like currently am facing issue where my all C drive space is eaten up. let say i free up 2 GB space in my C drive then within 20 minute it will be gone and C drive will show out of space so currently am unable to trace down the process which is eating space. so this feature to record data written by process will be very useful to see which process is doing massive writing.

thanks

**Comment by dmex** [comment]
> Disk tab we have column where it shows total average data written by process

The disk tab is based on single files not processes. It can't show totals for a process because the same process will be shown 1000 times for 1000 files and the same total for 1000 entries won't make sense.

Totals for processes are shown on the processes tab with the Disk columns:
![image](https://user-images.githubusercontent.com/1306177/188506149-970b3615-b501-47ee-a873-7372585e7de0.png)

You can also see the totals on the System Information window Disk graphs (mouse over the graphs to see the process, double click to open the process properties):
![image](https://user-images.githubusercontent.com/1306177/188506289-c12d557a-6e5d-45e1-b3ea-d76867fb3cb5.png)

There's also the Disk and Network tab showing disk usage for the process:
![image](https://user-images.githubusercontent.com/1306177/188506344-5ac92d72-9d81-4701-bc8b-030fc47b3bd9.png)

Also the Statistics tab for more disk statistics:
![image](https://user-images.githubusercontent.com/1306177/188506447-25498902-984f-4584-bf13-a490a3724c58.png)

**Comment by dmex** [comment]
👍

**Comment by darkworks** [comment]
thanks :)

**Comment by darkworks** [comment]
@dmex  so looks like when processhacker is opened it pre load Disk total bytes by process. i think it will also be good idea if we have column where it shows newly written in the current process hacker opened session. i think its implementation is easy
Total Disk bytes at start of processhacker session - current disk bytes = newly written bytes in the current session of process hacker

![image](https://user-images.githubusercontent.com/12841788/188552955-a6334752-37a3-4814-8197-59291b00a8b4.png)

it will be useful to debug things to see who is doing the current writing on disk mostly at the moment 

thanks
