### ISSUE TITLE
wierd auto-change ImagePath when chnage Start type of drivers

### ISSUE THREAD

**Issue by amymor** [winsiderss/systeminformer#1371]
### Brief description of your issue

i noticed sometime when i change Start type of drivers, the PH automatically changes ImagePath, it seems add `\Systemroot\` to the beginning of address, for example `System32\drivers\vdrvroot.sys` changed to `\Systemroot\System32\drivers\vdrvroot.sys` and also if i change it further i noticed it changed to `\Systemroot\Systemroot\System32\drivers\vdrvroot.sys `.
a week ago i disabled some Bluetooth drivers, so i checked them and noticed that `\Systemroot\` added to their ImagePath too.

### Steps to reproduce (optional)

changing Start type to something like System start.

### Environment (optional)

```shell
Process Hacker 3.0.4953
Windows 10 20h2
```

**Comment by dmex** [comment]
> PH automatically changes ImagePath

PH doesn't do anything with the filename. It just copies whatever from the textbox and passes it directly to ChangeServiceConfig:

![image](https://user-images.githubusercontent.com/1306177/189136268-3c9b9fc4-bb0f-40ee-b794-b74fc38f826d.png)

You can check the sources here:
https://github.com/winsiderss/systeminformer/blob/dee9746f44b24888d68e438934d231c2e850fd45/SystemInformer/srvprp.c#L499-L525

> it seems add \Systemroot\ to the beginning of address

The [ChangeServiceConfig](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-changeserviceconfigw) function is adding \systemroot\ to the filename and it does this when the service start type was changed to BootStart.

ChangeServiceConfig is built into Windows and mandatory for changing service configuration and we can't prevent the function from modifying file paths. You could modify the registry directly but you would have to immediately reboot since service information is cached by services.exe 

>  i noticed it changed to \Systemroot\Systemroot\

I wasn't able to reproduce this issue. ChangeServiceConfig appends \Systemroot\ but then doesn't append it a second time.

**Comment by dmex** [comment]
You can also reproduce the same behavior using Windows commands. For example:

1) Open elevated command prompt
2) Execute `sc config SERVICENAME start=boot`

The sc command is included with Windows and also uses ChangeServiceConfig, so it also changes the path to include \systemroot\
