### ISSUE TITLE
Uninstallation removes everything from the installation directory

### ISSUE THREAD

**Issue by Majorro** [winsiderss/systeminformer#1377]
### Brief description of your issue

I forgot to create distinct folder for processhacker when installed, so it had some files and folders along with processhackers'. When I uninstalled it, everything except installer, which was in the same directory was erased.

### Steps to reproduce (optional)

1. Install to folder which has some files/folders
2. Uninstall

### Expected behavior (optional)

files/folders are not deleted

### Actual behavior (optional)

files/folders are deleted

**Comment by dmex** [comment]
The uninstaller is supposed to remove the directory otherwise what's the point? 

If we don't remove the directory then we'll get complaints about junk getting left over after uninstalling.

**Comment by Masamune3210** [comment]
Yeah this just sounds like you ignored the assumption literally every installer/uninstaller makes. Dont install programs in shared folders

**Comment by Majorro** [comment]
> I would expect this from any program sharing directories?

I'm sure that I've seen "safe" uninstallation behavior several times

> Were the files moved to the recycle bin or permanently deleted?

Permanently deleted

**Comment by dmex** [comment]
> I'm sure that I've seen "safe" uninstallation behavior several times

These uninstallers hardcode filenames and forget to remove older files from older versions.

* The problem is when some users install version X.X.X and then don't update for years. 
* We'll rename or remove files in version Y.Y.Y but they never installed that version, so those files were never removed. 
* Years later they install version Z.Z.Z and it starts crashing or has some other issue because the file that should have been removed 5 years ago by the previous updates wasn't removed.

I considered hard-coding all the names and only removing those files but:
* Some users have plugins-extra plugins and we can't include them all.
* If you configure symbol server support without a directory then Windows dbghelp.dll downloads PDBs into the directory (several GB of files).
* Some other programs can leave junk in the directory.

Simply removing the installation directory is what the large majority of users expect when they uninstall. It's not expected that anyone installs the program into a common directory shared with other files/programs because due to the legacy design of Windows multiple programs sharing the same directory creates DLL planting/security issues and [DLL hell](https://en.wikipedia.org/wiki/DLL_Hell).

Executables should always have their own separate directories.

> Permanently deleted

I could change this to move files to the recycle bin so at least if anyone does this again they can undelete those files?

**Comment by ge0rdi** [comment]
Installer can eventually show a warning if the target folder exists already.
Though it should be shown only in case of clean install as in case of upgrade it is expected that the folder does exist.

**Comment by dmex** [comment]
> if the target folder exists already.

It should probably show a warning when you're installing into a directory that isn't empty?

**Comment by ge0rdi** [comment]
Yup, that would be even better.

**Comment by Majorro** [comment]
>I considered hard-coding all the names and only removing those files

Isn't possible to track files somhow? Maybe using some sort of lightweight local storage? Or program creates-deletes files often?

**Comment by dmex** [comment]
> program creates-deletes files often

There's been a dozen or so changes over the last 14 years and there's more planned in the future and it's not feasible to track files over such long time periods... It's more simple, easy and much more reliable to clean the installation directory entirely than hundreds of lines of spaghetti code to handle older versions and new versions.

> show a warning when you're installing into a directory that isn't empty

Fixed in bdb10b18b5d90697a2f146b674fd278e21a343e2
