### ISSUE TITLE
Run as this user... bug?

### ISSUE THREAD

**Issue by AnorBanantje** [winsiderss/systeminformer#1423]
### Brief description of your issue

When i want run cmd as another user in Windows Server 2019 i get black screen cmd which works but i can't see what i type in this window.

![3](https://user-images.githubusercontent.com/109865290/195802285-7ed94362-f0d4-46a3-98fb-1bf3dff4ad02.PNG)

### Steps to reproduce (optional)

1. Search explorer.exe process of another user
![1](https://user-images.githubusercontent.com/109865290/195801812-9ec6f394-7cdb-4dda-9cfb-a805aaf133ab.png)

2. Run as this user CMD in your session
![2](https://user-images.githubusercontent.com/109865290/195801830-7e8e3ef0-de2f-46fe-8688-bb62f1ef0d19.png)

3. You get so cmd screen (it works but you can't see it in your session)
![3](https://user-images.githubusercontent.com/109865290/195801849-6879ed2f-8980-465e-9507-4e6e34b7b956.PNG)

### Expected behavior (optional)

Normal cmd graphic

### Actual behavior (optional)

cmd with black screen but works i written in die cmd   whoami > c:\test.txt answer was impersonated username

![3](https://user-images.githubusercontent.com/109865290/195801562-819c8bb4-5fa6-4d60-9806-37accc40d7a8.PNG)

### Environment (optional)

```shell
SystemInformer 3.0.9873.5346 self compiled today from main
Windows Server 2019
```

**Comment by dmex** [comment]
> SystemInformer 3.0.9873.5346 self compiled today from main

Can you try the latest stable v2.39 and confirm it also has the same issue? 
https://processhacker.sourceforge.io/downloads.php

The nightly is using an entirely different runas implementation which might be missing support for RDP and it would help to know if those versions are working or if all versions have the same issue.

**Comment by diversenok** [comment]
The screenshot looks very much like starting a process with a logon SID in its token that doesn't match the current window station's SID. Just saying.

**Comment by dmex** [comment]
@diversenok The current desktop DACL doesn't have enough privileges for the administrator by default and there wasn't any error message. I've fixed this in the latest nightly.

**Comment by diversenok** [comment]
Interesting, I didn't notice that admins don't get full access to the window station/desktop. What I meant with the previous comment is that during logon, winlogon assigns the current window station and desktop the logon SID from the session's token (we can observe it via [GetUserObjectInformation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getuserobjectinformationw) with `UOI_USER_SID`). It also adds a full access ACE with this logon SID into the DACLs.

@dmex Maybe we should use the same logic and add an ACE with the logon SID of the new token/process instead of granting access to Everyone. We can get the new logon SID directly from [LogonUserExExW](https://learn.microsoft.com/en-us/windows/win32/secauthn/logonuserexexw) or read it from the new process's token before it starts.
