### ISSUE TITLE
Process Hacker System Tray Icon not Functional

### ISSUE THREAD

**Issue by morrowindmemes** [winsiderss/systeminformer#1443]
Process Hacker version: 3.0.4953

Windows version:  Dev Preview Build 25227.1000

Right clicking the system tray icon does nothing so closing the program from the tray is impossible to do. The info pop-up works great though.

![image](https://user-images.githubusercontent.com/81074108/197250537-1ace4669-be18-4c22-be2c-7be81faa2622.png)

**Comment by dmex** [comment]
> Dev Preview Build 25227

Sorry we don't support prerelease builds of Windows.

>  Right clicking the system tray icon does nothing

I tested a 25227 VM and the right-click works fine? The last 10 or so insider builds were crashing for everyone when they tried to click or drag the system tray so it's probably another insider bug.

**Comment by KastriotH** [comment]
Process Hacker version: 3.0.4953

Windows 11 beta 22623.875

Same issue, non functional tray icon, if i can support PH then you can try at least to fix it.

**Comment by Masamune3210** [comment]
No, as stated before, Beta versions of Windows are not supported due to their fast paced changes and inclusion of code and behavior decisions that might never see the light of Retail. If the issue persists when the update hits Retail, report it then. Otherwise, you should expect programs to not completely work correctly when you are running a non-Retail OS version

**Comment by KastriotH** [comment]
The irony is i am using nightly build of PH so it's fast/slow? paced same as W11 beta, but it's OK i understand.

**Comment by dmex** [comment]
> The irony is i am using nightly build of PH so it's fast/slow? paced same as W11 beta, but it's OK i understand.

Microsoft are currently updating the system tray with each new insider build at this moment:

![image](https://user-images.githubusercontent.com/1306177/199056163-b20819f3-aa71-45a0-b94d-c664f0a59b09.png)

If somethings broken then you need to install a newer insider build or opt-out of insider builds.

**Comment by morrowindmemes** [comment]
The new taskbar is rewritten in XAML and it's presence not just in the Dev builds but also in the beta builds which means it will eventually be in the W11 %99. I understand the policy of yours "no support for experimantal builds" and fully support it but maybe this could be an exception?

**Comment by Masamune3210** [comment]
From experience it is seldomly a good idea to try to program for a target still on wheels so to speak. Just because it's likely to hit Retail doesn't mean it's totally set in stone yet

**Comment by morrowindmemes** [comment]
Yeah, you're right if you look at this perspective. It's not a huge deal for me, i just pinned the PH to the start menu and use it from there.

**Comment by dmex** [comment]
> I understand the policy of yours "no support for experimantal builds" and fully support it but maybe this could be an exception?

There's nothing to support or change. Microsoft hasn't added/updated/changed anything for third parties and the Shell_NotifyIcon function hasn't changed either so there's nothing for us to update.

I have 25231 in a VM and tray icons/menus work fine... If they're not working on your insider build it's because your insider build is corrupted or an older version with missing functionality and you'll have to wait for Microsoft to add the functionality.

**Comment by KastriotH** [comment]
All before this i couldn't rearrange icons then i tried vivetool /disable /id:38764045 and after this i could rearrange them again, then MS updated taskbar and i couldn't show menus on PS, now used again c:\vivetool\vivetool /enable /id:38764045 thinking it will unstuck menus but no luck so it seems now i got total fuckup.
