### ISSUE TITLE
Multi-Column Support

### ISSUE THREAD

**Issue by TheSQLGuru** [winsiderss/systeminformer#1453]
### Description of the feature, modification, idea or suggestion

Please provide multi-column sorting for all grids in the new System Informer product. Thanks for your consideration!

**Comment by dmex** [comment]
> multi-column sorting

The different types of data are incompatible with multi-column sorting largely because sorting requires changing the row positions.

For example the first column is sorting process names:
chrome.exe
explorer.exe
notepad.exe

The second column is sorting memory usage:
explorer.exe - 5MB
notepad.exe - 100MB
chrome.exe  - 1024MB

Now the first column is no longer getting sorted alphabetically even though it's sorting by multiple columns. If we attach some type of 'weight' to the column to obscure the column data then we end up with without sorting either memory or names:

explorer.exe - 5MB
chrome.exe  - 1024MB
notepad.exe - 100MB

The solution to this problem is disable the 'Allow only one instance' checkbox in settings and then run multiple copies of System Informer at the same time. You can sort multiple columns separately and alt-tab between the two instances when needing to compare the values and you can save all the different multi-column sorting configurations using the Main menu > View > `Save column set` option 👍
