### ISSUE TITLE
Systreminformer has problems reducing working set of system procresses

### ISSUE THREAD

**Issue by kotenok2000** [winsiderss/systeminformer#1526]
### Brief description of your issue

When i highlight all processes and reduce working set i get access denied from:
System
Registry
smss/exe
wininit/exe
csrss.exe
sgrmbroker.exe
services.exe
memory compression
svchost
and several other system processes
I have kernel driver enabled.
It didn't happen on process hacker.
Also it aborts process on every encounter of access denied.

### Expected behavior (optional)

All processes with exception of System idle process and Interrupts can have their working set reduced.

### Environment (optional)

```shell
3.0.5578
Microsoft Windows [Version 10.0.22621.819]
```

**Comment by Masamune3210** [comment]
Trying to reduce the working set of some of these processes, especially System Idle, doesn't make sense. They are pseudo-processes, they don't actually exist as normal processes

**Comment by kotenok2000** [comment]
I do not try to reduce system idle.

**Comment by Masamune3210** [comment]
Misread System as System Idle, but the point still stands. Stuff like Registry and System are treated specially by the system

**Comment by kotenok2000** [comment]
Did you cut functions  from kernel driver?

**Comment by Masamune3210** [comment]
I am not one of the devs, you will have to wait for one of them to chime in on that one. I just know that certain processes are handled specially by the system, and those two are some of them

**Comment by DavidXanatos** [comment]
> Did you cut functions from kernel driver?

The new driver respects MSFT's guidelines for not being able to mess with protected processed, otherwise it wouldn't have gotten a signature.

**Comment by dmex** [comment]
> The new driver respects MSFT's guidelines for not being able to mess with protected process

EmptyWorkingSet is the only exception for protected processes:
https://github.com/winsiderss/systeminformer/blob/d243fcb2f287eca7c01970a332bac9cf4dcb478f/KSystemInformer/process.c#L889-L924

It's handled directly by the driver without input from usermode:
https://github.com/winsiderss/systeminformer/blob/d243fcb2f287eca7c01970a332bac9cf4dcb478f/KSystemInformer/process.c#L996-L1011

> Did you cut functions from kernel driver?

There were extra checks for the buffers. This was fixed in the latest nightly build 👍

![image](https://user-images.githubusercontent.com/1306177/209471692-99f6ad62-b5ea-4acf-84b4-91dff705db6e.png)
