### ISSUE TITLE
Settings history

### ISSUE THREAD

**Issue by alabotski** [winsiderss/systeminformer#1565]
### Description of the feature, modification, idea or suggestion

Is it possible to add saving the history of settings (for example, 5 files)

Sometimes I get this error (often lately)
And I have to start setting up the application from the very beginning

![image](https://user-images.githubusercontent.com/439337/212466647-d20085d8-5651-4bc5-9f2d-f1a0798cbc14.png)

**Comment by dmex** [comment]
> Sometimes I get this error (often lately)

Can you upload a copy of the corrupt settings file?

> Is it possible to add saving the history of settings

This type of bug has only happened once in 14 years and last time it was caused by an antivirus product. I don't want to make changes to something that's not broken. There's something that has to be causing the corruption.

**Comment by alabotski** [comment]
@dmex 
Give me some time.... I deleted the wrong settings file
I'll try again to reproduce this error

**Comment by alabotski** [comment]
It's me again

![Windows 2023-02-19 09-34-03](https://user-images.githubusercontent.com/439337/219933507-4f0d4bb7-ea7e-4f4d-a695-2cb2b02b4b19.png)

And broken settings file (change extension)
[SystemInformer.exe.settings.xml.txt](https://github.com/winsiderss/systeminformer/files/10776314/SystemInformer.exe.settings.xml.txt)

**Comment by dmex** [comment]
@alabotski 

System Informer was terminated while it was saving the settings file and half of the file is missing.

Have you used any system/tweaking/performance tools or modified any timeouts/shutdown related?

**Comment by alabotski** [comment]
@dmex 
Yes, I configured something similar when reinstalling Windows
But! For all time and with all programs, this problem is only with systeminformer

Is it really such a heavy operation to form an xml and save it on disk? What is missing in the allotted time?

And the second question, why change the settings file every time? Isn't it logical to do this after changing the settings?

**Comment by dmex** [comment]
> Yes, I configured something similar when reinstalling Windows

What values did you configure so I can test this?

> why change the settings file every time? Isn't it logical to do this after changing the settings?

There's no notification for some settings like resizing the window or columns so the settings are saved when exiting the application.

> Is it really such a heavy operation to form an xml and save it on disk?

No, saving the settings is less than 1 second.

> For all time and with all programs, this problem is only with systeminformer

You're probably corrupting other processes but they're not showing a message so you never know.

Task manager applications are configured by default to be the very, very last application terminated by Windows during shutdown so you're able to investigate or debug applications blocking shutdown.

The default shutdown timeout is 60 seconds. You've configured ? 10 seconds and other processes take 9.5 seconds and we're getting half a second or 500ms before getting terminated.

**Comment by alabotski** [comment]
@dmex  Thanks for answer

I have changed the following value
**HKEY_CURRENT_USER\Control Panel\Desktop\HungAppTimeout	REG_SZ	1000	10**

Also, you need “heavy” program
For example, I can reproduce this crash with Cisco Any Connect

If I close Cisco, wait and then turn off Windows 10 – all works fine
BUT
But if I immediately turn off the computer without completing Cisco (the shutdown operation takes 30–60 seconds), then it is highly likely that after the reboot the config file System Informer will already be broken

**Comment by dmex** [comment]
> HungAppTimeout

@alabotski  Did you also configure `AutoEndTasks`?

**Comment by alabotski** [comment]
My value

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Desktop]
"AutoEndTasks"=dword:00000001
```

**Comment by dmex** [comment]
Shutdown changes:

* System Informer and Task Manager are the last applications to shutdown by design to support cancel debugging. Shutdown cancel debugging is now disabled by default. System Informer is now the first application to get shutdown unless cancel debugging is enabled by changing `EnableLastProcessShutdown` to 1.

* [Shell_NotifyIcon](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyiconw) was deadlocking System Informer for 8 seconds during shutdown because tray icons were waiting for a response from explorer.exe but explorer.exe had already been shutdown. This is now skipped on shutdown since explorer.exe is already terminated making cleanup pointless.

* Flushing and removing the ETW sessions was deadlocking System Informer anywhere from 2-10 seconds during shutdown because the shutdown generated events that were re-filling buffers. This is now skipped on shutdown since these buffers/events are owned by the kernel and deleted on shutdown.

* WM_QUIT (termination) and WM_ENDSESSION (shutdown) both had the exact same cleanup during shutdown. The cleanup included tray icons, ETW sessions, application settings and updater tasks. WM_ENDSESSION (shutdown) is now handled separately from termination and skips everything except saving application settings.

* The UserNotes plugin database was always saved on termination. It's been updated and now only saves when something has actually changed.

Ideally the application settings would only be saved when changing settings/resizing windows/resizing columns instead of when the application exits but this will take some time to update everything.

--------------

> add saving the history of settings (for example, 5 files)

We could add an option to create a backup of the application settings but shouldn't be needed after the above changes. Let me know if you're still seeing any corrupted settings messages and I'll re-open the issue 👍
