### ISSUE TITLE
Detours fail in latest release

### ISSUE THREAD

**Issue by TheEragon** [winsiderss/systeminformer#1572]
### Brief description of your issue

If you have Mitigation policy and Dark theme enabled System Informer reports an error that it failed to commit detours.

![image](https://user-images.githubusercontent.com/5801389/214049799-0b6c6fd3-7042-41ed-95a0-1662859d6908.png)

The bug was introduced in this commit https://github.com/winsiderss/systeminformer/commit/cfdc49ebcb73ba039d4e35ca1c3a84f486a329b9.

The issue is in that detours try to allocated RWX memory in https://github.com/winsiderss/systeminformer/blob/master/tools/thirdparty/detours/detours.cpp#L1349 which fails due to mitigation that prohibits allocating such region (PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON).

Possible solution is to init hooks before mitigations are applied.

**Comment by dmex** [comment]
> Possible solution is to init hooks before mitigations are applied.

The mitigation policy is enabled using IFEO key during process creation so we're not able to override it.

> The issue is in that detours try to allocated RWX memory

I'm deprecating the mitigation option because the kernel driver has better mitigations than these policies.

**Comment by ge0rdi** [comment]
> I'm deprecating the mitigation option because the kernel driver has better mitigations than these policies.

Is that a good idea to deprecate good thing (mitigation policies are good thing no matter of what driver does) just because of _dark theme_ (or streaming mode)?

**Comment by dmex** [comment]
> mitigation policies are good thing

Microsoft doesn't allow programs to specify the policy using IMAGE_LOAD_CONFIG_DIRECTORY during process creation so you have to configure it at runtime and third parties are exploiting this to disable the policy by simply deleting the IFEO registry key, hooking RegOpenKey and returning success or hooking CreateProcess and stripping out the PROC_THREAD_ATTRIBUTE_MITIGATION_POLICY flag.

The only two good policies were ExtensionPointDisable and MicrosoftSignedOnly but Microsoft recently started allow anything with UiAccess=TRUE in the executable manifest to automatically bypass both policies so they're useless.

> no matter of what driver does

I don't see any issues with deprecating those IFEO mitigations. The driver has these same mitigations but also enforces protection during both creation and runtime and it also has some extra advanced features like virtual-secure-mode isolation ([MmProtectDriverSection](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmprotectdriversection)) similar to security products.

> just because of dark theme (or streaming mode)

Yep. The alternative is using SetWindowsHook but even when specifying the current process that function increases the time required to handle messages and keyboard/mouse input for the entire system (bad for online gaming and performance). Local hooks with detours have none of those issues since they're in-process and I'll likely be using them to fix issues like #1513 and for some other new features.

**Comment by ge0rdi** [comment]
Could you at least keep the mitigation option (even disabled by default and in advanced options), so that it can be enabled by those who want it?

**Comment by dmex** [comment]
> Could you at least keep the mitigation option (even disabled by default and in advanced options), so that it can be enabled by those who want it?

It doesn't work so there's no point keeping the option. If you want mitigations then use commands built into Windows: https://learn.microsoft.com/en-us/powershell/module/processmitigations/set-processmitigation

```
Set-ProcessMitigation -Name SystemInformer.exe -Enable ForceRelocateImages,RequireInfo,BottomUp,HighEntropy,DisableExtensionPoints,BlockDynamicCode,MicrosoftSignedOnly
```
