### ISSUE TITLE
3.0.10753.6226 crash when open network tab

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1627]
### Brief description of your issue

3.0.10753.6226 crash when open network tab

### Environment (optional)

```shell
3.0.10753.6226 crash when open network tab
win7 x32
```

**Comment by Biswa96** [comment]
Windows 7 is not supported. Please see the supported Windows versions here https://systeminformer.sourceforge.io/downloads.php

**Comment by wincmd64** [comment]
[Open System requirements](https://github.com/winsiderss/systeminformer)

System requirements
Windows 7 or higher, 32-bit or 64-bit.

**Comment by Biswa96** [comment]
I assume the README was not changed after the project migration. Please wait for maintainers.

**Comment by dmex** [comment]
> README was not changed after the project migration

Fixed

> win7 x32

MSVC is going to break or drop support and we won't be able to maintain Windows 7 support. We've already been forced to drop support for the driver because of signing issues and MSVC changes and the remaining support for Windows 7 is practically non-existent (no driver or tooling etc) and you should keep using Process Hacker v2.39 as the last supported Windows 7 version (driver support etc).

**Comment by wincmd64** [comment]
pls keep win7 support
just delete Network tab

**Comment by Masamune3210** [comment]
It's unfortunately not that easy
