### ISSUE TITLE
After enabling the column showing GPU utilization and waking up from sleep mode, the NVDisplay.Container.exe process has been consistently occupying a significant amount of CPU.

### ISSUE THREAD

**Issue by ShenHongFei** [winsiderss/systeminformer#1628]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/15074472/222963508-a5b0625a-d45b-4755-b135-c383d1b69b26.png)

![image](https://user-images.githubusercontent.com/15074472/222963462-6e2b5d31-aaf9-4146-a686-dd7cd4861c1a.png)

### Environment (optional)

```shell
SystemInformer: 3.0.6226 (0f2db4c)
Windows: 22621.1344
Nvidia Driver: RTX 3080 v531.18
```

**Comment by Vasilich** [comment]
And where is the problem description?
I do not see any from screenshots posted.

**Comment by dmex** [comment]
> enabling the column showing GPU utilization ... the NVDisplay.Container.exe process has been consistently occupying a significant amount of CPU

We query GPU utilization from kernel directly using `D3DKMTQueryStatistics` and this function doesn't interact with NVDisplay.Container.exe or require graphics drivers/software installed. 

CPU accounting is also very accurate and System Informer is always billed for any utilization it causes otherwise some innocent program would get blamed for utilization by some other process. If you're seeing high utilization by NVDisplay.Container.exe then it's accurate and not caused by other processes.

> waking up from sleep mode, the NVDisplay.Container.exe process

It's a bug in some telemetry component completely unrelated to System Informer:
https://www.reddit.com/r/nvidia/comments/11e7ukr/game_ready_driver_53118_faqdiscussion/jam16da/

You should rollback to v528.49 or delete the dll 👍
