### ISSUE TITLE
Behavior:Win32/DefenseEvasion.A!ml

### ISSUE THREAD

**Issue by rxznve** [winsiderss/systeminformer#1631]
### This program is dangerous and executes commands from an attacker.

Windows 10 Defender quarantines **System Informer** reporting threat **Win32/DefenseEvasion.A!ml**

file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\System Informer.lnk
file: D:\Programs\Debugging\System Informer\SystemInformer.exe

I am sure that this is a **false positive**, but still I decided to report it.

**Comment by dmex** [comment]
It's a false positive. 

You can report false positive detections to Microsoft by selecting `Home Customer` and attaching the binary here:
https://www.microsoft.com/en-us/wdsi/filesubmission

The same way you report false positives via that link is how we report false positives and you can submit reviews without waiting for us to submit them. Defender does seem to be broken AF at the moment because submitting just the one systeminformer.exe file instantly breaks Defender saying too many files but it's only 1 file 🤷‍♂️

![image](https://user-images.githubusercontent.com/1306177/223566048-61b45392-6d03-42ef-b2d7-f032112778c2.png)
