### ISSUE TITLE
Architecture column empty

### ISSUE THREAD

**Issue by 5Z-A** [winsiderss/systeminformer#1638]
### Brief description of your issue

Since at least version 3.0.6210 nightly, the "Architecture" column on "Processes" tab does not get populated.

### Steps to reproduce (optional)

On "Processes" tab, add "Architecture" to active columns.

### Expected behavior (optional)

The column should be populated with values ("x64", "x86") like in older versions.

### Actual behavior (optional)

The column is empty.

### Environment (optional)

```shell
System Informer 3.0.6264 nightly
Windows 10 version 21H2 build 19044.2604 x64

System Informer 3.0.6210 nightly
Windows 10 version 22H2 build 19045.2364 x64
```

**Comment by dmex** [comment]
> Windows 10 version

Microsoft only added process architecture for Windows 11.

> The column should be populated with values ("x64", "x86") like in older versions.

We emulate process architecture on Windows 10.

> Since at least version 3.0.6210 nightly, the "Architecture" column on "Processes" tab does not get populated.

I removed the emulation for Windows 10 because it was unnecessarily mapping hundreds of images when the feature was disabled.

> Fixed in ver 3.0.6295.

The emulation performance was fixed. It's basically the same information as the Bits column on Windows 10 and the real architecture on Windows 11.
