### ISSUE TITLE
Setup file not deleted after update, which prevents autoupdating next time

### ISSUE THREAD

**Issue by Evengard** [winsiderss/systeminformer#1645]
### Brief description of your issue

When SystemInformer is autoupdating, a systeminformer-setup.exe file is created inside the program directory. This file is not deleted after the autoupdate, which prevents further autoupdates (they fail with an error) until I manually remove this leftover file.

This issue was nonexistant when the project was still named Process Hacker.

### Steps to reproduce (optional)

1. Autoupdate SystemInformer
2. Observe the systeminformer-setup.exe file in the program directory
3. Wait for another autoupdate
4. Try to update - the update will fail
5. Remove systeminformer-setup.exe from the program directory
6. Try to update again - it will be successful
7. Observe the systeminformer-setup.exe in the program directory again

### Expected behavior (optional)

The systeminformer-setup.exe should be automatically deleted either after an update or before starting a new one.

### Actual behavior (optional)

The leftover systeminformer-setup.exe is preventing the autoupdate, errorring out.

### Environment (optional)

```shell
System Informer
Version: 3.0.6303 (8f3d619)

Windows 11 Enterprise
```

**Comment by dmex** [comment]
> The systeminformer-setup.exe should be automatically deleted

The setup file doesn't get deleted because it's also the uninstaller and repair install option, If you delete the file then you won't be able to repair or uninstall.

> prevents further autoupdates (they fail with an error) until I manually remove this leftover file

The updater moves the current setup.exe into the trash and renames update.exe to setup.exe before each update. The setup.exe version should always have the same version as all the other binaries in the folder. Moving the current file into the trash should always succeed (even when something else is using the file) unless the you have a custom directory permission preventing access?

> Try to update - the update will fail

What error are you seeing when trying to update?

**Comment by Evengard** [comment]
Seems like the error is gone now. Maybe got fixed along some partly related changes. Maybe I got some weird misconfiguration. All is well right now though.
