### ISSUE TITLE
Disk read/write/total rate average values

### ISSUE THREAD

**Issue by 5Z-A** [winsiderss/systeminformer#1654]
### Brief description of your issue

This will be tough to describe...

Disk tab, Read/Write/Total Rate Average columns: the values displayed appear to be the calculated average values for a (very) long past period.

### Steps to reproduce (optional)

An example: even for processes closed tens of second ago, these average values are still displayed. The values are slowly, but constantly decreasing, before finally disappearing from the list.

### Expected behavior (optional)

 Instead of the behaviour described above, I believe they should be the average calculated since the last refresh.

### Environment (optional)

```shell
System Informer 3.0.6384 x64 nightly
Windows 10 x64 ver 21H2 build 19044.2728
```

**Comment by dmex** [comment]
> the values displayed appear to be the calculated average values for a (very) long past period.

This is how Microsoft designed the API and show values in their software. If you launch Resource Monitor from the Tools menu and select the Disk tab you'll see the exact same values:

![image](https://user-images.githubusercontent.com/1306177/226761249-46070219-c09f-435b-b9ed-3480d1e9086f.png)

> they should be the average calculated since the last refresh.

They should but this is a limitation of the API from how Microsoft implemented the feature. We could remove items more quickly but then you won't be able to see any activity so we're just using the same values/timeouts as Resource Monitor?

The disks shown on the system information window are realtime and more reliable for statistics while the disk tab is better suited for viewing recent file activity instead of statistics.
