### ISSUE TITLE
W11 Pro: Trojan:Win32/Sabsik.TE.B!ml detected by Windows Defender out of the blue  [Fixed]

### ISSUE THREAD

**Issue by UglyStuff** [winsiderss/systeminformer#1665]
Hi everyone, 

A long-term Process Hacker user, I got fed up with antivirus software blocking/quarantining/nuking it so I just dropped using it at all, until I discovered System Informer, and I thought those security alerts were a thing of the past. 

I was wrong, alas. 

Like the title says, Windows Defender just quarantined System Informer due to the (alleged) presence of Trojan:Win32/Sabsik.TE.B!ml. 

I updated SI yesterday to the latest version, and nothing happened then, but just a few minutes ago, after a restart, I was notified by WD that System Informer had been quarantined; I tried to reinstall using the installer in the Program folder, but it just didn't. 

I hailed the dev on Twitter about it, but I'd like to be on the safe side here: could it be real, or is it just Windows Defender being its usual overzealous self?

**Comment by dmex** [comment]
> it just didn't

You need to restore or whitelist otherwise defender silently blocks the files:
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

>  just Windows Defender being its usual overzealous self?

Yep

You can report false positives here:
https://www.microsoft.com/en-us/wdsi/filesubmission

> B!ml

Machine learning... TLDR:

![image](https://user-images.githubusercontent.com/1306177/228653906-c30566b2-6811-431a-b511-3925fece2a76.png)
