### ISSUE TITLE
Unable to run/open non .exe files from run dialog

### ISSUE THREAD

**Issue by harig** [winsiderss/systeminformer#1669]
: version 3.0.6427 (latest build available at the moment)
- Run systeminformer with administrative privileges
- Open systeminformer's run (Ctrl+R) dialog 
- Uncheck the administative privileges box.
- Type diskmgmt.msc and press enter

An error dialog saying that %1 is not a win32 application is shown when this is attempted. The disk management MMC is opened if adminstrative privileges checkbox is ticked.  Should this trigger an error instead of opening the app which would request for elevation there after?

For a non-executable file like a PDF/text file, it is the same error but when adminstrative privileges is ticked, the error dialog says that no file association could be found. Though in the Windows Run dialog, typing the path and pressing enter open the PDF/text file in the default application associated. Shouldn't this just work in both cases?

**Comment by dmex** [comment]
> Should this trigger an error instead of opening the app which would request for elevation there after?

Elevation is preformed by ShellExecute and you don't see an error in this case because it supports non-executable formats like diskmgmt.msc

> For a non-executable file like a PDF/text file, it is the same error but when adminstrative privileges is ticked, the error dialog says that no file association could be found

The run dialog uses two separate functions [CreateProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) and [ShellExecute](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecuteexw).... CreateProcess doesn't support elevation and only supports executable formats. ShellExecute supports elevation and non-executable formats when they have file associations.

> An error dialog saying that %1 is not a win32 application is shown when this is attempted

The run dialog determines which function to create the process by calling [GetBinaryTypeW](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getbinarytypew) but we're not using this function for the moment.

**Comment by dmex** [comment]
Fixed in latest nightly build 🥳
