### ISSUE TITLE
Hidden taskbar - systray preview hardly accessible

### ISSUE THREAD

**Issue by TairikuOokami** [winsiderss/systeminformer#1671]
### Brief description of your issue

This was not an issue before, it started with the latest versions.
It is not possible to preview all other systray icons, they are hidden.
If the preview window is locked, moved up, unlocked, it moves back down.
6433 at least added 1 sec delay, it is possible to choose, which icon to display.
![capture_04022023_120740](https://user-images.githubusercontent.com/81519712/229346459-fe668025-f6b6-4fef-90df-d3dc4eed9e77.jpg)

### Steps to reproduce (optional)

Automatically hide the taskbar

### Environment (optional)

```shell
System Informer 3.0.6433
Windows 11 Home 22621.1485
```

**Comment by gggirlgeek** [comment]
Not sure if this is what the OP is referring to but I've always had trouble catching the tray icon with my mouse (in order to move it) before the preview pops up. It's especially annoying when I display multiple icons. It becomes a game of cat and mouse (kind of fun actually. 😸 ) Using a low-quality mouse, however, is impossible. I have this program on my media server so am often trying to make due with a remote control in my living room.... Well, the neighbors think I'm always cussing at my husband but I swear I'm not! 😬 It's System Informer!

If this is not the same issue I'll search, then post a new issue. Thank you all.

**Comment by dmex** [comment]
> Not sure if this is what the OP is referring to

The window overlapping the taskbar when changes position and set to hide automatically.

> I've always had trouble catching the tray icon with my mouse (in order to move it) before the preview pops up. 

Are tray icons moving around the screen? I don't understand what's `catching the tray icon`?

**Comment by dmex** [comment]
@TairikuOokami 

Fixed in latest nightly build 🥳
