### ISSUE TITLE
Add "start minimized" startup option

### ISSUE THREAD

**Issue by as-muncher** [winsiderss/systeminformer#1672]
3.0.6433

I see the "start hidden" option, but I'm not even sure there's a tray icon for System Informer.  Certainly, there is no underline under the System Informer icon which I have pinned to my taskbar.  When I have "start hidden" enabled, when the computer starts up, I have to click on the System Informer icon anyways to load it, so why not make a "start minimized" option?

**Comment by dmex** [comment]
> why not make a "start minimized" option

This is what the tray icon does?

**Comment by as-muncher** [comment]
ok, perhaps my mistake then

**Comment by as-muncher** [comment]
Perhaps, then, when I double-click the tray icon, it will show as maximized instead of minimized?  That is what happens when I have System Informer to start hidden.

**Comment by dmex** [comment]
The window state is persistent and using the last recorded size and position when the application exited. It's starting maximized because that was saved to settings. You can just change the window position then exit and restart the program to update the persistent settings with a new location.

**Comment by as-muncher** [comment]
After using System Informer's "start hidden" option, I still think it's a great idea to have a "start minimized" option, so I don't have to fish it out of the system tray, right-click, Show System Informer.  I also think that, even though System Informer starts in the system tray, it might even be responsible for still stealing focus away from Fallout 4 when I start that up.

**Comment by dmex** [comment]
@as-muncher 

You can start the application minimized by right-clicking the icon > properties > selecting Minimized:

![image](https://github.com/winsiderss/systeminformer/assets/1306177/56baa5fa-f549-437c-8fd6-4b768d813666)


> even though System Informer starts in the system tray, it might even be responsible for still stealing focus away from Fallout 4 

System Informer would be stealing focus from everything not just one program? Applications started in the system tray do not have foreground focus which is required to change the foreground window: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks 

You should also probably disable the new Windows "optimizations" forcing blt-model presentation with borderless windows since Fallout 4 predates these changes. It would probably be trying to switch to exclusive or flip presentation then getting reset/overridden by Windows (resetting the activation/state/focus and cursor capture etc... normally used with exclusive).

**Comment by as-muncher** [comment]
ok, thanks for the detailled response
