### ISSUE TITLE
Accessing system threads

### ISSUE THREAD

**Issue by ftwcyzo** [winsiderss/systeminformer#1703]
### Description of the feature, modification, idea or suggestion

Could access system threads and change affinity, thread priority, I/O priority, etc on Process Hacker v2.
Can't do that anymore on this version.
Also should add ability to save changes to affinities, etc to specific threads because you couldn't do that on old versions.

**Comment by jxy-s** [comment]
> Could access system threads and change affinity, thread priority, I/O priority, etc on Process Hacker v2.
Can't do that anymore on this version.

This is by design. System threads are created under the System process which is a protected process. Write access to protected processes is now strictly controlled, by design.

> Also should add ability to save changes to affinities, etc to specific threads because you couldn't do that on old versions.

Is there a reasonable or good justification to save this state per-thread? Could maybe do it for named threads or by the start address... but it seems quite unnecessary from my point of view.
