### ISSUE TITLE
do we have an ETA for a stable release?

### ISSUE THREAD

**Issue by cablop** [winsiderss/systeminformer#1730]
i used ProcessHacker for years, but it is so hard to deal with the system believing it is malware, so a stable release is something we really want

**Comment by dmex** [comment]
We originally planned for a stable release in January... There were some issues blocking a stable release:

- [x]  Microsoft sent an agreement to sign that was missing 20 pages.
- [ ] [Blue screen/Bug checks caused by Third parties](https://github.com/winsiderss/systeminformer/issues?q=is%3Aopen+is%3Aissue+label%3A%22third+party%22).
- [ ] #1668

There's ongoing discussions with 25 companies causing various issues... The large majority have been resolved and there will be a stable release soon™

**Comment by cablop** [comment]
Huh, it is a lot of administrative stuff to get it done. I really hope everything goes on track and we see a stable release soon.

I honestly think this is the best app of its kind by far.
