### ISSUE TITLE
Flagged on over 29 Anti-virus software.

### ISSUE THREAD

**Issue by rcsw1** [winsiderss/systeminformer#1732]
### Brief description of your issue

https://www.virustotal.com/gui/file/28042dd4a92a0033b8f1d419b9e989c5b8e32d1d2d881f5c8251d58ce35b9063 -I scanned the file on virustotal and this is what came up.

**Comment by dmex** [comment]
> processhacker-2.39-setup.exe

Process Hacker has been discontinued.

**Comment by Vasilich** [comment]
@rcsw1 
moreover, have you ever read what kind of "flagged" are those? "Riskware"/"unwanted"/"hacktool"/"ProcessHacker"
So those antivirus products just don't like the amount of possibilities that ProcessHacker can do. So what - why do you care that some AV do not like such powerful tools like this? It is like to flag VisualStudio because with it you can create dangerous tools...

**Comment by as-muncher** [comment]
2023-08-22, microsoft antivirus is killing system informer, as in deleting the files
