### ISSUE TITLE
System Informer crashes all the time

### ISSUE THREAD

**Issue by go-xoxo** [winsiderss/systeminformer#1775]
### Brief description of your issue

I just wanted to report this bug I experience since updating to the last nightly Version. I had some issues already with the application since approx. 2 Months ago, when the application crashed on certain setting like when switching on "dark mode". With this last update.. crashes happen all the time.. almost any action causes that, like opening settings or even when enlarging to fullsize window. I'm ready to provide more information if that helps and if you would tell me what you need. Thx.

### Environment (optional)

```shell
System Informer Nightly 3.06806
Edition	Windows 11 Pro Insider Preview
OS build	25300.1000
Experience	Windows Feature Experience Pack 1000.25300.1000.0
```

**Comment by dmex** [comment]
> OS build	25300.1000

This is an old build from February. The latest insider build is 25393?

>  some issues already with the application since approx. 2 Months ago, when the application crashed on certain setting like when switching on "dark mode". With this last update.. crashes happen all the time.. almost any action causes that,

Microsoft added debug assertions for functions like NotifyServiceStatusChangeW and since these callbacks are invoked at random intervals they were crashing the program whenever a service decided to invoke the callback.

There wasn't any point doing anything because Microsoft regularly change something for one insider build and remove/fix the issue in the next build... those assertions were removed after they finished doing whatever it was they were doing 🤷

>  if you would tell me what you need

You need to update your insider build?
