### ISSUE TITLE
Systeminformer Crashes when new service was created

### ISSUE THREAD

**Issue by Fiz-Victor** [winsiderss/systeminformer#1787]
### Brief description of your issue

Systeminformer Crashes when new service was created.
This does not happen all the time, but randomly.

Stack Dump:
```
STACK_TEXT:  
000000a7`480ff1d0 00007ffa`80fa96a4     : 00000000`00000000 000001eb`ea5549d0 00007ffa`7eb25210 000001eb`e2020000 : ntdll!RtlUnsubscribeWnfNotificationWaitForCompletion+0xa51ab
000000a7`480ff210 00007ff6`1bd52466     : 00000000`0000001e 000001eb`ead02000 0000ffeb`ffffffff 00000000`00000000 : sechost!UnsubscribeServiceChangeNotifications+0x14
000000a7`480ff240 00007ffa`80fa8f8d     : 00501100`00001100 00000000`00000008 000001eb`ef7cd0e0 0000ba5a`d49b34da : SystemInformer!PhGetServiceChange+0x1526
000000a7`480ff270 00007ffa`810995b4     : 41c64e6d`a07f7845 41c64e6d`a07f7845 000001eb`ef7cd500 00000000`00000003 : sechost!ScServiceChangeNotificationCallback+0x2d
000000a7`480ff2a0 00007ffa`8109902a     : 000001eb`ead0ec50 000001eb`ef7cd0a0 00000000`00000000 00000046`00000000 : ntdll!RtlpWnfWalkUserSubscriptionList+0x3e4
000000a7`480ff410 00007ffa`81098d72     : 000001eb`ead0ec50 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlpWnfProcessCurrentDescriptor+0x116
000000a7`480ff460 00007ffa`8109b294     : 000001eb`e2210a50 00000000`00000000 000001eb`e2210bd8 00000000`7ffe0386 : ntdll!RtlpWnfNotificationThread+0x82
000000a7`480ff4c0 00007ffa`8109ee1f     : 000001eb`e2202440 000001eb`e22d1db0 00000000`00000000 000001eb`e2202440 : ntdll!TppExecuteWaitCallback+0xa4
000000a7`480ff510 00007ffa`7f823db1     : 00000050`00000050 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!TppWorkerThread+0x46f
000000a7`480ff800 00007ffa`81094801     : 00000000`00000000 00000000`00000000 00000000`00000000 80000000`00000800 : kernel32!BaseThreadInitThunk+0x21
000000a7`480ff830 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

### Steps to reproduce (optional)

1. [Running Core Temp](https://www.alcpu.com/CoreTemp/)

### Expected behavior (optional)

System informer shows the "service created message"

### Actual behavior (optional)

System informer crashed

### Environment (optional)

```shell
System Informer 3.0.6806 (efc8ced)
Microsoft Windows Inider 10.0.25393.1
```

**Comment by dmex** [comment]
> Microsoft Windows Inider 10.0.25393.1

These crashes only affect insider builds. There's some sort of issue with the OS crashing any application calling [UnsubscribeServiceChangeNotifications](https://learn.microsoft.com/en-us/windows/win32/services/unsubscribeservicechangenotifications) and there's some other weird deadlock with [NtCreateSection](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntcreatesection).

You'll need to wait for a patch from Microsoft or revert to an earlier insider build.

**Comment by Fiz-Victor** [comment]
Thx. It seems microsoft has fixed the service creation and NtCreateSection bug, but SI still crashed when service got deleted.

**Comment by gggirlgeek** [comment]
I'm having crashes on two different computers. It's when I either click in the search bar, and sometimes when I simply raise it from the system tray. System informer freezes, gives a crash error, then offers to restart, rinse and repeat over and over. It's only with v6.0.6806. When I go back to v3.0.6550 the crashes stop on both computers. **The message said something about the kernel**. I use the same settings .ini file on both. I really don't want to reinstall them, enable memory dumps, collect logs, etc, since others have already done it. But I will if it's really helpful.

SystemInformer v3.0.6806

Systems:
Acer Aspire A-515-54G laptop
i5-8265U CPU
20GB-DDR4-2666
Onboard Intel-UHD GPU 1GB
Win10pro64

Custom Desktop Build
MSI Pro Z690-A LGA1700
i5-12400F 2.4Ghz 6-core
16GB DDR5-4800
AMD RTX 3060-Ti 8GB
EVGA 750W 80+Gold
Win10Pro64

**Comment by Fiz-Victor** [comment]
It is on win 10 so prob create a separate issue maybe

**Comment by gggirlgeek** [comment]
Oh. OK. I didn't catch the Insider part. I wasn't sure where to post because my problem is so consistent across 2 computers that I figured it's the same as most others are having with that particular SI build. Didn't want to duplicate issues. I guess I will post it and do the debug. FYI, my Windows exact build:

Windows 10 pro build: 19045.2846

Windows Feature Experience Pack 120.2212.4190.0

**Comment by dmex** [comment]
Fixed in the latest build updates 👍
