### ISSUE TITLE
Display File Paths for Unloaded Modules

### ISSUE THREAD

**Issue by R-udren** [winsiderss/systeminformer#1834]
### Description of the feature, modification, idea or suggestion

I noticed in the `ProcessName` - `Miscellaneous` - `Unloaded Modules` section, it displays unloaded modules with their names, sizes, and memory base addresses. I suggest adding the file path for those modules or DLLs. It would be really handy for analysis. Is this something that could be possible?

**Comment by dmex** [comment]
> suggest adding the file path for those modules

We don't show the path because Windows only records 32 characters of the filename for unload events:

```cpp
typedef struct _RTL_UNLOAD_EVENT_TRACE 
 { 
     PVOID BaseAddress; 
     SIZE_T SizeOfImage; 
     ULONG Sequence; 
     ULONG TimeDateStamp; 
     ULONG CheckSum; 
     WCHAR ImageName[32]; 
     ULONG Version[2]; 
 } RTL_UNLOAD_EVENT_TRACE, *PRTL_UNLOAD_EVENT_TRACE; 
 ```

> Is this something that could be possible?

* The `ImageName`, `TimeDateStamp` and `SizeOfImage` fields can be combined to download the original DLL from the Microsoft symbol server using this format:
```
https://msdl.microsoft.com/download/symbols/FileName/TimeDateStampSizeOfImage/FileName
```

For example this link downloads the original ntdll.dll: 
```
https://msdl.microsoft.com/download/symbols/ntdll.dll/7A9F67F2214000/ntdll.dll
```

* Search the disk for a DLL containing `ImageName`, `TimeDateStamp`, `SizeOfImage` and `CheckSum`.

The first option is only supported with Microsoft binaries and they're safe to download, load and query the image. The second option works with any third party application but searching would be a 50/50 chance of locating the correct image (i.e. weird sub directory or multiple images with identical values)?

**Comment by R-udren** [comment]
I was specifically interested in third-party DLLs.
