### ISSUE TITLE
Signer and verification status are empty in "Services" tab

### ISSUE THREAD

**Issue by dragokas** [winsiderss/systeminformer#1863]
### Brief description of your issue

The following fields are always empty in the "Services" tab:
 - Verification status
 - Verified signer

### Steps to reproduce (optional)

Go to "Services" tab. RMB - Choose columns...:
 - Verification status
 - Verified signer

### Expected behavior (optional)

Fields should display signer name and EDS result.

### Actual behavior (optional)

Empty fields.

### Environment (optional)

System Informer ver. 3.0.7256 ([121e1d2](https://github.com/winsiderss/systeminformer/commit/121e1d2)) - Nightly
 - Windows 7 x64
 - Windows 10 x64

**Comment by jxy-s** [comment]
Make sure this is enabled:
![image](https://github.com/winsiderss/systeminformer/assets/11687482/d3857c2d-03ab-4f67-bda6-490dcbec7e0e)

**Comment by dragokas** [comment]
Thank you. It works.
Can we do a label "Disabled by options" to prevent confusing? - similar to what we see in "VirusTotal" column when the option "Enable virustotal scanning" is not enabled. In that case we see the label: "Scanning disabled". That would prevent similar questions from other users.

**Comment by dragokas** [comment]
Also, when user are adding these new columns he is expecting it to work just right now without need to search for "something" "somewhere" to enable it finally.
Maybe it make sense to enable that option automatically as soon as user are adding one of these column in "Services" tab?

**Comment by jxy-s** [comment]
This commit will show when the settings are disabled in the cell, similar to how we show "Image coherency support is disabled." when "Check images for coherency" isn't checked: https://github.com/winsiderss/systeminformer/commit/4d24bcbc118b5ba51c375ef928256ae5b0e0d81e

Automatically changing settings when columns are changed has some complications since some settings are shared between different UI elements. I don't think that's practical approach to take.

**Comment by dmex** [comment]
Fixed with 4d24bcbc118b5ba51c375ef928256ae5b0e0d81e (latest nightly)
