### ISSUE TITLE
System Informer crashes from time to time

### ISSUE THREAD

**Issue by Puncia** [winsiderss/systeminformer#1928]
### Brief description of your issue

I'm not sure what the cause is but I get this crash report maybe like 10 times per day.
It doesn't seem related to anything I do. It seems to be happening after updating to https://github.com/winsiderss/systeminformer/commit/965bf7bdddb6201195ac7135a89662325d4f6d4d (3.0.7353)

I generated a Normaldump but I'm not sure if it contains sensitive info. If it doesn't please let me know and I will provide it.

![Untitled](https://github.com/winsiderss/systeminformer/assets/4633311/1c553359-02b2-4842-b46a-11285f0caa59)

**Comment by w4po** [comment]
+1
I had the same problem, right after I updated to (3.0.7353)

Steps to reproduce: I tried to search for a process name and as soon as I typed the first character the app crashed,
I reopened the app again, this time I tried to click on the Case-Sensitive button and the Regex button, but the app crashed again and again.

I then tried to check for an update, and there was none of course, but suddenly the issue was solved without me changing anything???!

**Comment by Still34** [comment]
Same thing here; still can't consistently reproduce. It's been crashing all the time for me over the last while. More than willing to provide crash dump (privately).

**Comment by Puncia** [comment]
My WinDbg output is basically identical to the one above, including the stacktrace, so I think it's safe to assume it's the same issue.

**Comment by Slopz** [comment]
Experiencing the same thing!

**Comment by jxy-s** [comment]
If possible, please email me a full dump johnny.shaw@live.com.

**Comment by jxy-s** [comment]
Fixed via: https://github.com/winsiderss/systeminformer/commit/106ac124c1fe9536a3997d4ddd55f181ebe78ec4

**Comment by jxy-s** [comment]
`3.0.7412` -> `Help > Check for updates` 👍
