### ISSUE TITLE
Unable to load kernel driver 

### ISSUE THREAD

**Issue by jacob4202** [winsiderss/systeminformer#1986]
### Whenever I open system informer this pops up 
Windows 10 IoT Enterprise LTSC 2021

<img width="296" alt="Capture" src="https://github.com/winsiderss/systeminformer/assets/131926340/dac60280-c8a5-4644-9a4d-38b36314675a">

### Environment (optional)

Windows 10 IoT Enterprise LTSC 2021

**Comment by jacob4202** [comment]
Whenever I open system informer this pops up

**Comment by dmex** [comment]
Your version of Windows 10 is too old.

**Comment by jacob4202** [comment]
> Your version of Windows 10 is too old.
OS Name	Microsoft Windows 10 IoT Enterprise LTSC 2021

**Comment by DavidXanatos** [comment]
please fix IMHO SI should support at least the two latest LTSC builds so in this case 2019 and 2021

**Comment by jxy-s** [comment]
> SI team doesn't want to support

To be clear, it's not that we don't want to support it. It's simply too much of a time investment with our current tooling. I am working on better automation to fill that gap.

**Comment by lonewolf0708** [comment]
This just started today after a cumulative update

Capture

![image](https://github.com/winsiderss/systeminformer/assets/51030924/aa2a8f4f-0f77-4e7b-89c7-7b544c1f2e20)


Steps to reproduce (optional)
Open System Informer with Kernel driver checked in Options

Expected behavior (optional)
Silently load

Actual behavior (optional)
prompts about unsupported version

Environment (optional)
Windows 11 Professional 23H2 build 22631.3296

**Comment by MagicAndre1981** [comment]
After each Patchday the team needs to update some dynamic data based on the new kernel.

**Comment by DaveSkooby** [comment]
Uninstalling KB5035942 allowed the driver to load for me

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823
