### ISSUE TITLE
Error updating to latest version 

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#2023]
### Brief description of your issue

I got a notification of a new update 3.0.7545, but this update fails

![image](https://github.com/winsiderss/systeminformer/assets/8274816/6c569f07-f801-4f23-9d2a-8a6c5b388ad9)

Here are the errors I see with procmon:

![image](https://github.com/winsiderss/systeminformer/assets/8274816/d6c2a329-c472-4f44-94f0-bc3cf570d89f)

### Environment (optional)

```shell
Windows 10 22H2 19045.4170

System Informer
Version: 3.0.7526 (863858c)
```

**Comment by MagicAndre1981** [comment]
I have installed SI in non default dir at

`C:\Programme_portable\systeminformer_Portable`

**Comment by jxy-s** [comment]
Something is broken, I pulled the nightly build, we're investigating.

**Comment by Biswa96** [comment]
I am running that exact nightly build and it updated automatically without any issue. Should I revert back to older version?

**Comment by jxy-s** [comment]
No, you'll be fine when the next nightly is published.

**Comment by jxy-s** [comment]
Subtle difference between `realloc` and `RtlReAllocateHeap` here.

The bug was introduced by the following change:
https://github.com/winsiderss/systeminformer/commit/91b27d66deeb48595104861a0ba2c0e0f06d0dbb#diff-035c9d3b9551386274aaecd75380b633e32cbff66126164728b9b24a628602d5R596

And is fixed by: https://github.com/winsiderss/systeminformer/commit/92cd97f42f60ebc72db1f27b65858cc1ce1f2f8c

Another nightly is baking.

**Comment by jxy-s** [comment]
`3.0.7546` 👍

**Comment by MagicAndre1981** [comment]
> `3.0.7546` 👍

update works fine 🙌
