### ISSUE TITLE
Show NPU like Taskmgr

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#2038]
### Description of the feature, modification, idea or suggestion

[Taskmgr](https://www.dell.com/support/kbdoc/en-us/000223944/how-to-identify-ai-enabled-windows-computers?lwp=rt) in Windows 11 24H2 shows NPU graph

![image](https://github.com/winsiderss/systeminformer/assets/8274816/79c64cc4-a7fe-44fa-9164-ce58a685c29a)

Can you also add this to syteminformer for the new "AI" PCs where MS requires NPU?

**Comment by MagicAndre1981** [comment]
Ok, I see you added it: https://github.com/winsiderss/systeminformer/commit/518f95bad3184e18218dc6e164042a815f976a37

How does it look? Can you please post a picture on what it shows?

**Comment by jxy-s** [comment]
![image](https://github.com/winsiderss/systeminformer/assets/11687482/8bc45226-5928-4569-aadd-846f590446ba)

**Comment by MagicAndre1981** [comment]
ok, you now have a CoPilot+ ARM64 Laptop. How does it perform? How well does the arm64 version of VS2022 run?

**Comment by jxy-s** [comment]
VS works good. A few things in my development workflow need attention:

1. Neovim does not yet have a native version. It works in emulation but some of my setup/plugins gives errors. Haven't had an opportunity to investigate the cause.
2. Some VS22 extensions are missing and not yet supported on ARM64. Like trailing white space and spell check. VSVim works, thankfully.
3. I need to go look at CustomBuildTool and make sure it's using the new native compiler from the latest VS instead of x64 under emulation.
4. Bazel currently has some quirks if you end up running under emulation.

Those are all relatively minor things that I'm confident will get sorted out in time. Overall the machine exceeds my needs/expectations on performance and the battery life is stellar.

**Comment by MagicAndre1981** [comment]
ok, MS added new NPU statistics in recent Insider Build:

> We’re updating Task Manager to provide better insight into NPU usage for PCs that include an NPU. New optional NPU and NPU Engine columns are now available on the Processes, Users, and Details pages. The Details page also adds NPU Dedicated Memory and NPU Shared Memory optional columns to give you deeper visibility into how workloads are using NPU resources. Additionally, if there are neural engines that are part of a GPU, they will now appear on the Performance page, providing a more complete view of AI‑related system activity.

https://learn.microsoft.com/en-us/windows-insider/release-notes/experimental-future-platforms/preview-build-29576-1000#task-manager

Maybe also add this, too to SI.

**Comment by jxy-s** [comment]
> We’re updating Task Manager to provide better insight into NPU usage for PCs that include an NPU. New optional NPU and NPU Engine columns are now available on the Processes, Users, and Details pages. The Details page also adds NPU Dedicated Memory and NPU Shared Memory optional columns to give you deeper visibility into how workloads are using NPU resources. 

We've had this for a long time:

<img width="1257" height="328" alt="Image" src="https://github.com/user-attachments/assets/c6122608-fa7d-45c0-8810-b214146c7841" />


> Additionally, if there are neural engines that are part of a GPU, they will now appear on the Performance page, providing a more complete view of AI‑related system activity.

I'm not sure I have hardware to look into the other use case. But unless they changed something internally they should just show up here as an "NPU":

<img width="901" height="514" alt="Image" src="https://github.com/user-attachments/assets/426a8239-8276-4a57-a85a-e967867d2198" />

**Comment by MagicAndre1981** [comment]
ok, thanks. I have no system with NPU, so I can't check it.
