### ISSUE TITLE
kernel driver is not yet supported

### ISSUE THREAD

**Issue by KingAmirTheHunter** [winsiderss/systeminformer#2062]
### Description of the feature, modification, idea or suggestion

System Informer

Unable to load kernel driver

Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.3527
System Informer 3.0.7578 (ff4fc00)

[ ] Don't show this message again  [OK]

**Comment by jxy-s** [comment]
@KingAmirTheHunter this is a duplicate os: https://github.com/winsiderss/systeminformer/issues/2062

Your kernel is already supported but you must switch to the `Canary` channel for driver support - `Help > Switch update channel`

@Sakana24 I'm not sure your problem is related to the driver? I will need more information. Please open a new issue with some more details on what is crashing, or email me the dump file.
