### ISSUE TITLE
Add option to speed up programs

### ISSUE THREAD

**Issue by thewanderingtraderm** [winsiderss/systeminformer#2110]
### Description of the feature, modification, idea or suggestion

Add option to change the speed of programs, similar to cheat engine's speedhack feature

**Comment by dmex** [comment]
> cheat engine's speedhack feature

"speedhack" would be flagged as a cheat and is out of scope for this project. Displaying values like the system timer resolution would be in scope but modifications/cheating are out of scope.

> Add option to change the speed of programs

Windows 11 already includes this 'feature' by default since it's using a synthetic timer which doesn't seem to work when hyper-v is disabled. After ~ 24 hours uptime and/or resuming from sleep, the timer and interrupt resolution starts changing randomly causing all sorts of weird timing or performance issues (dependence on TSC? https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps#hardware-timer-info)

* Windows 11 (15.625 resolution is expected but < 15.625ms sleep isn't normal)

![image](https://github.com/user-attachments/assets/074f9333-0685-483c-8646-19dda0d9351d)
![image](https://github.com/user-attachments/assets/f19e4f87-51e2-4306-9559-d091a6b2152f)

----------------------------------------------

* Windows 10:✅

![image](https://github.com/user-attachments/assets/2fc548cc-c7be-49af-bfce-e1722415a850)

Intel processors seem to be more affected by the volatile changes with lower scheduling and higher clock drift. Disabling synthetic timers using `bcdedit /set useplatformtick yes` seems to fix the issue.
