### ISSUE TITLE
Left-right scroll bar needed

### ISSUE THREAD

**Issue by as-muncher** [winsiderss/systeminformer#2223]
### Brief description of your issue

I need to be able to scroll left and right.

### Steps to reproduce (optional)

Perhaps increase the font size.  

### Expected behavior (optional)

I should be able to scroll left and right to see the other columns.

### Actual behavior (optional)

![Screenshot 2024-10-02 183312 - Copy](https://github.com/user-attachments/assets/f46fb8fc-b7d9-4ad4-a600-d9c3cece74d1)

### Environment (optional)

```shell
system informer 3.0.7660 (08de40d) on win 11 x64
```

**Comment by dmex** [comment]
You can't have the Name column that large because it's a fixed column. Fixed columns are always visible when scrolling so the scrollbars are only visible for non-fixed columns. 

So either make the Name column smaller:

![image](https://github.com/user-attachments/assets/12b1c246-55fa-45cd-bbe4-53de1d5e2465)

Always visible --------------------------------- ^^^^^ Scrollbar starts here

Or you can disable the fixed columns by changing setting `ProcessTreeListNameDefault` to 0
