### ISSUE TITLE
Options buttons grayed out for all plugins

### ISSUE THREAD

**Issue by jtabox** [winsiderss/systeminformer#2303]
### Brief description of your issue

Hey, I'm a bit confused regarding the plugins' functionality, and I don't know if it's a bug or I'm supposed to take extra steps to activate some option or whatever. There's no available information about it.

I started by trying to figure out how to enable the VirusTotal scanning functionality, and looking at other users' UIs, apparently I don't even have the relevant section in the Options window at all, since from what I understand, there should be an `OnlineChecks` option below `NetworkTools`?:
[<img src="https://github.com/user-attachments/assets/86a3f1b4-9dfb-4c85-aeb4-e305966e925c" height="450"/>](https://github.com/user-attachments/assets/86a3f1b4-9dfb-4c85-aeb4-e305966e925c)

Looking further in the `Plugins` option, it seems like they're all activated (or at least none are disabled), but when I try to open their options, every single `Options...` button is grayed out, for every plugin:
[<img src="https://github.com/user-attachments/assets/85c0244c-fda9-409e-b834-f420751eb93e" height="450"/>](https://github.com/user-attachments/assets/85c0244c-fda9-409e-b834-f420751eb93e)

I have activated the `Enable plugins` option amongst others, but it doesn't seem to help:
[<img src="https://github.com/user-attachments/assets/5e4cce5d-9ca8-42b0-9f70-5ab8e7c84f6a" height="450"/>](https://github.com/user-attachments/assets/5e4cce5d-9ca8-42b0-9f70-5ab8e7c84f6a)

I apologize if this isn't a bug, but I wasn't able to find any related info about it.

### Expected behavior (optional)

Mostly to be able to activate VirusTotal online scanning, but also figure out if the various plugins have options I can change.

### Environment (optional)

```shell
System Informer 3.1.24298.0 Release (running as Administrator)

Windows 11 Pro [Version 23H2 / OS build 22631.4541]
```

**Comment by Almighty188** [comment]
Try going to Options -> Advanced -> EnableDefaultSafePlugins and change the value to 0 from 1 and see if it makes a difference or not.

**Comment by dmex** [comment]
> there should be an OnlineChecks option below NetworkTools?:

The page was removed because OnlineChecks only had one option and an entire settings page didn't make sense. 

> ooking further in the Plugins option, it seems like they're all activated (or at least none are disabled), but when I try to open their options, every single Options... button is grayed out, for every plugin:

Plugin settings are integrated into the UI.

The options button is only for backwards compatibility with legacy plugins from 5-10 yeas ago. They didn't have settings integration and that was the only method to access those settings at the time. 

For example the original settings window:

![image](https://github.com/user-attachments/assets/c0f7fd72-752e-4e43-adfa-558ce5791968)

The settings button was the only method to access plugin settings:

![image](https://github.com/user-attachments/assets/b2cb8717-9c61-4312-bf1b-4072d0c02b16)

![image](https://github.com/user-attachments/assets/5f75f5b5-ed2a-44cd-bf9e-42868e482066)

![image](https://github.com/user-attachments/assets/3a1f3a03-fb8b-40a6-bf94-e78671bb362a)
