### ISSUE TITLE
Figuring out a way to support multi-select for thread affinity changes

### ISSUE THREAD

**Issue by ghost** [winsiderss/systeminformer#583]
Hello

I've just figured out about this program recently and the huge fact it can manipulate per-thread CPU affinity for an end-user without the access to source code or having to manipulate the memory of the application, which I dreamed of for about a year but never knew it actually existed. It has already assisted me in performance diagnostics while beta testing a computer game, but has also proven to be a useful workaround until the game gets fixed.

However, the target program spawns around 20 threads if not more and I have to manually set affinity on each thread every time I restart the program, this is quite a time consuming process and if it does have potential to be a workaround, it would not be a practical one for most people to use on a daily basis.

I wanted to first check out if this was attempted before and what's the stance of this community on how this should be done.

Additionally there should also be an "Affinity" column in the process properties Threads tab to see each thread's affinity more easily and quickly.

**Comment by altimumdelta** [comment]
![Priority not consistent?](https://i.imgur.com/xElgrht.png)

Not sure if this is a bug or not with Process Hacker.

Now I see details below could also be added to columns, but Affinity is not there either, room for improvement.

**Comment by dmex** [comment]
> Now I see details below could also be added to columns, but Affinity is not there either, room for improvement.

This was added years ago. You need to add the `Ideal Processor` column as seen here on the right:

![image](https://user-images.githubusercontent.com/1306177/77809278-b9c37f80-70da-11ea-8f13-bf8f0df23aec.png)

**Comment by altimumdelta** [comment]
Yeah, I don't see the "Options" Button and no search box ... I'll check the version what did I install.

**Comment by altimumdelta** [comment]
Well the easiest way would be to just overwrite any pre-set thread affinity with the new one without having to figure out a way to practically show the varying states of the selected ones, that would work for me but probably not here.

I wanted to take a look at the code to see if I can help but I actually never dealth with vanilla C before.

Finally managed to get it to run on this Win10 14939 machine with VS2017 and retarget to SDK 17763 and having to delete `WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_3` from http.c in phlib because it was tripping as an "undeclared identifier"

I do actually have VS2019 on another secondary machine but didn't took the time yet to reinstall it here.

Now I'm trying to find where the right-click context menu code is located.

**Comment by altimumdelta** [comment]
The best way would be to be able to automatically intercept new threads in real-time and set the custom affinity with filters such as if it's "`Start Address`" contains a certain string, rather than starting a program in one state like a game's main menu, setting affinity to those threads at that time, newly created threads wouldn't otherwise be included as the program's operation changes unless you painstakingly doing this constantly as threads disappear and reappear.

**Comment by altimumdelta** [comment]
> > Now I see details below could also be added to columns, but Affinity is not there either, room for improvement.
> 
> This was fixed years ago. You need to add the `Ideal Processor` column as seen here on the right:
> 
> ![image](https://user-images.githubusercontent.com/1306177/77809278-b9c37f80-70da-11ea-8f13-bf8f0df23aec.png)

Well when I change affinity, the Ideal Processor values remain the same.

**Comment by dmex** [comment]
> when I change affinity, the Ideal Processor values remain the same.

I've fixed the values in the latest nightly build. You can update using the Help > Check for updates menu 👍

**Comment by altimumdelta** [comment]
> You should be changing the priority of the process not individual threads hence why changing multiple threads has never been supported - It can be done just confused why it's needed? The game should also be using MMCSS for its threads which is required for games on Windows.

I'm doing beta-testing with the help of per-thread CPU affinity changes at least to prove a point, demonstrate a performance annomaly and compare results between different affinity settings. It may not be really needed out there, it's needed for me for this purpose right now and because it's the only way to test these kind of particular performance issues with the program and can even be used as a workaround that's why I need to increase the iteration time before continuing, I started looking at the code but it'll really take a while before I have any idea what to do, I'm not a real C/c++ programmer even tho I do basic things from time to time.

So for many months I just spent looking for a program that can do per-thread CPU affinity changes and I finally found it to my great surprise and happyness. As I predicted, I went testing the same moment and I already found(proved/demonstrated) an issue using this feature and reported it as a bug report to the developers.

I haven't touched priorities yet because that's just not sure enough, that is not affinity, I really need a particular thread to stay only on 1 or two CPU cores and that different components depending on what I'm testing are isolated from each other and don't execute on the same CPU cores, at all times without any bouncing which would affect testing and the performance diagnosis results.

The developers were impressed enough they invited me to become a memeber of the official community beta-tester team (access to pre-release builds) :)

The ultimate solution would be for an utility to scan for a particular process name as well as threads it's spawning and apply the appropirate custom affinities, this may be outside of this program scope, but what perhaps could be is simply by using profiles and triggers such as a time interval and manual like so: "Set all Program.exe thread affinity which Start Address string begins with "ntdll.dll@" to CORE1".
In my case there's already some threads that work differently but have the same Start Address so this isn't full proof, for fine tuned adjustments I would turn off the trigger interval to keep applying this (every 500-1000 ms or so) and then once most of the threads have their affinity set automatically, I would modify individual ones further, again saving a lot of time each session.

**Comment by dmex** [comment]
> there's already some threads that work differently but have the same Start Address

It wouldn't be possible to persist affinity changes for multiple threads across multiple instances and restarts based on the start address because its common for processes to have a specific thread start for multiple threads.

It might work 80% of the time for that one process but wouldn't work consistently enough for other processes and users would file issues about it not working.

> I wanted to take a look at the code to see if I can help

I can make it possible to change affinity for multiple threads if it would help? It just won't be possible to save those changes and apply them automatically when the process/system restarts.

**Comment by altimumdelta** [comment]
Yeah that would definitely help big time, I could select 10 of them, set them all to CORE0 for example.

**Comment by altimumdelta** [comment]
Hmm ... I knew it I should have checked before ... so who maintains the sourceforge processhacker site now ... the W32.64 guy seems inactive around here since 2016 ... where the hell did my donations go ...

**Comment by dmex** [comment]
> so who maintains the sourceforge processhacker site now

That's me. I maintain the site and project.

> where the hell did my donations go

They go to towards the project?

**Comment by altimumdelta** [comment]
The guy that the paypal email goes to is another account which hasn't contributed code to this project since 2016. Can you confirm you got the receipt on paypal, the message mentions per-threads specifically.

**Comment by dmex** [comment]
> The guy that the paypal email goes to is another account which hasn't contributed code to this project since 2016, his last activity was in December 2019 on something totally unrelated. 

His contracts and NDA with Microsoft prohibited contributions to this project since he worked on the HyperV team and had access to Windows source code.

He still indirectly contributes to the project fairly regularly and I'm still using a lot of his stuff to implement these changes and features. It might not look like it from his github commits but the framework, controls, OS support, macros, structures, objects, types etc... are things that I regularly use to create new features and functionality are his code and work based on his input.

> The guy's website was also not updated since 2016.

I'm responsible for updating the websites. It used to be here (https://wj32.org/processhacker/) but I've been working on updating the current sourceforge site.

You can still view the old site here:
https://processhacker.sourceforge.io/old_site/

The current site is less than 3 months old:
https://processhacker.sourceforge.io/

I'm still working on it and making changes. If something is missing or hasn't been updated then you should blame me :P

> I would expect some explanation whether the guy is still alive or around here and perhaps shares the donations or pays for the sourceforge hosting?

He's alive and they do go towards to the project.

> if it goes to someone who's gone for years that doesn't look right

Yeah I guess that's valid. He does still contribute. 

> you probably want to get this sorted out.

I put the donation links on the project page because I want the donations sent to Wen Jia. My paypal just returns an unknown error after login and their support staff are useless. 

> also noted in the donation message

If you've donated and wanted something done just give me a heads up via email :P

**Comment by altimumdelta** [comment]
I guess allright then :)

**Comment by dmex** [comment]
@altimumdelta 

The affinity dialog will show the number of selected threads in the window title and if all the threads have the same affinity the existing cores will be selected by default.

If all threads have different affinity and you select the Ok button they'll all reset to zero which currently returns an error dialog but this will need to be changed to check for changes.

Have you had any issues with affinity changes for multiple threads since these changes?

**Comment by altimumdelta** [comment]
@dmex I've tried it yes and it seemed to work fine for the normal multi-select. I understand it's hard to show the affinity of each of the threads specifically when selecting a lot of them so I understand it'll take some effort before we find some way.

Yes currently if the threads have mismatched priority then no CPU is check-marked, and clicking OK without selecting anything will produce an error dialog, but not a critical. I have thought that many of them would be selected if at least one thread uses a particular CPU, is that also on your mind?
Perhaps putting a thread count indication before or after the specific CPU label to indicate how many threads use CORE1 and/or CORE2 and so on.

I'll do another test run right now.
