### ISSUE TITLE
Increased CPU Usage

### ISSUE THREAD

**Issue by LIMUNADE** [winsiderss/systeminformer#595]
On system start up your program using around 12-15%. The only way to fix it is to open Process Hacker window. After that I can clearly see the difference on the graph and on the usage it's self. It goes back to normal 0.06% 

_Couple of things you should know:_ Program version - 3.0.2975
Windows Version - Win 10x64 1909

I'm using portable version and using task manager to run your program with administrative privilege on system launch.

**Comment by dmex** [comment]
> using task manager to run your program with administrative privilege on system launch.

Task Scheduler or Task Manager?

> On system start up your program using around 12-15%

Have you tried unchecking/disabling these two settings from the options window?

* Check images for digital signatures
* Check services for digital signatures

Some machines have performance issues with checking digital signatures (especially for services) and disabling these two options might help. Please let me know if it does :P

**Comment by LIMUNADE** [comment]
Task Scheduler. Sorry for the wrong name 

Both this options are turned off.

**Comment by dmex** [comment]
Are you using Avast antivirus or some other security product?

**Comment by LIMUNADE** [comment]
Nothing of this sort. I even removed windows defender competly because I value my computer resources.

**Comment by dmex** [comment]
Are you using any uxtheme patching for custom windows themes or non-default plugins for Process Hacker from plugins-extra or the forums?

**Comment by LIMUNADE** [comment]
[This is](https://cdn.discordapp.com/attachments/218029592382799874/698105270903111710/image.png) a whole plugin list and no. Never heard about uxtheme program.

**Comment by LIMUNADE** [comment]
Maybe [this graph](https://cdn.discordapp.com/attachments/218029592382799874/699687902761713823/image.png) would illustrate my issue better.

**Comment by dmex** [comment]
> Maybe this graph would illustrate my issue better.

I can't reproduce it. Can you enable multiple instances and check the thread stacks for the first instance?

e.g. after rebooting the first instance will be consuming CPU... start a second instance of Process Hacker and view the threads for the first instance. You should see the thread with the highest utilization and double click to open the thread stack.

Screenshot the stack for that thread(s) and upload them. You might need to click the Refresh button a few times and check for any changes / longer stacks and screenshot those too.

**Comment by LIMUNADE** [comment]
[This is ](https://cdn.discordapp.com/attachments/218029592382799874/700338798831075499/image.png)the result. And [this is](https://cdn.discordapp.com/attachments/218029592382799874/700338971351318578/image.png) the stack thread with the highest CPU usage. 

I waited for a while (my refresh rate was 15s). Only cpu result was jumping from 19 to 22 and cyclces delta were increasing in numbers. [Same window](https://cdn.discordapp.com/attachments/218029592382799874/700338971351318578/image.png) after 30+ min

**Comment by dmex** [comment]
@LIMUNADE 

I can't reproduce the issue. The only other report was from 2014 and we never found the cause:
https://wj32.org/processhacker/forums/viewtopic.php?t=1482

Your screenshot should be showing GetMesageW for the main thread but its showing DispatchMessageW... GetMesage blocks the thread when there are no messages but when there are messages we immediately call DispatchMessageW which indicates the message loop is processing window messages (which isn't something that happens when the window is invisible).

Can you try disabling the dark theme support in the options window since the dark theme sublasses the main window and could cause this issue?

The only other explanation would be some third party software spamming our window with unsolicited messages and causing the CPU usage. You could try doing the same as last time and execute a second instance of Process Hacker while the first one is consuming CPU usage and terminate any non-Microsoft process one by one and if the cpu usage suddenly stops it would be the offending process?

**Comment by LIMUNADE** [comment]
Well, default theme [made no difference](https://cdn.discordapp.com/attachments/218029592382799874/703557416897216562/image.png) in consumption of CPU. [Stack thread screenshot](https://cdn.discordapp.com/attachments/218029592382799874/703557973477425223/image.png). Maybe I should note that I don't use kernel-mode drivers.

**Comment by LIMUNADE** [comment]
After recent updates it's appears that the problem has been fixed. Thank you for you great software and constant updates.
