### ISSUE TITLE
System Information > Network: Display speeds also as Mbit/s

### ISSUE THREAD

**Issue by stdedos** [winsiderss/systeminformer#597]
Too frequently, I find myself needing to switch between bytes and bits for network speeds, depending on what am I actually looking for.

I would like that network speeds are toggleable between bytes and bits, and that this is _easily reachable_ (e.g. a checkbox in the System Information > Network tab)

**Comment by dmex** [comment]
The Mbit speed is always shown on the adapter details window?

**Comment by stdedos** [comment]
Can you please add a screenshot or a textual path on where that's supposed to be? 😕 

I am having trouble locating it. Preferably load your line so I can see where do you display Mbps network speeds (instead of MB/s)

**Comment by dmex** [comment]
![image](https://user-images.githubusercontent.com/1306177/78889166-8273ac00-7aa6-11ea-805f-e1a89503c294.png)

**Comment by stdedos** [comment]
This is link speed. I am talking about Sending / Receiving.
![image](https://user-images.githubusercontent.com/133706/78890854-0f9b0e80-7a6f-11ea-87d2-45c5ffba3079.png)
![image](https://user-images.githubusercontent.com/133706/78890858-13c72c00-7a6f-11ea-8077-44f1fd950c9e.png)

Figure out if you can see from here which is the image that I am doing a speedtest, and what is my line's BW in Mbps 😄

**Comment by dmex** [comment]
> I am talking about Sending / Receiving.

I haven't figured out how to correctly scale the size unit for Mbps values. The main problem is the scaling for mbps compared to sites like speedtest. They're using 100Mbps for comparison while we're using 1000Mbps - this ends up showing 0.70Mbps in Process Hacker and 7Mbps in Speedtest which isn't consistent and when compared to ethernet speed shows a wildly incorrect value.

**Comment by stdedos** [comment]
> They're using 100Mbps for comparison while we're using 1000Mbps - this ends up showing 0.70Mbps in Process Hacker and 7Mbps in Speedtest which isn't consistent and when compared to ethernet speed shows a wildly incorrect value. 

While I understand the logic... Is it okay that I don't understand why this makes sense? 😅

**Comment by Syst3mSh0ck** [comment]
This is why KiB and MiB data units were introduced. To help prevent the current confusion between bits and bytes. Traditionally bits are for comms and bytes are for storage. One megaBIT (Mb) is equal to 1,000 bits however one megaBYTE (MB) is equal to 1,024 bytes. Sending and Receiving would make more sense as KiB/MiB. Link speed should follow the same format. Alternatively just use Mbps (megabits per second) for comms and MB (megabyte) for storage since that's what most are familiar with. I work in telecoms and would expect data units for transmission speeds to always be in Bits. The current unit in use ie kB/s (kiloBYTE?) is equal to 8,000 bits ie 0.007629 of a megaBIT (Mb).

Here is a table for conversion to/from kiloBYTE to megaBIT: https://www.gbmb.org/mbps-to-kbs

Some information on KiB/MiB in context with other units: https://physics.nist.gov/cuu/Units/binary.html

I hope this helps. Thanks :)

**Comment by stdedos** [comment]
>  I work in telecoms and would expect data units for transmission speeds to always be in Bits.

I am an idiot user, who cannot count, and always gets his head messed up when converting amongst units - and I never know what unit I want to compare against another 😝😅

I only recently learned a "trick" to remember which unit scales on 2^x and which on 10^x 😄

**Comment by dmex** [comment]
I've fixed the display of bitrate prefixes for network devices 👍

**Comment by ceedveed** [comment]
I can't find this option to change to Mbit when looking at Network in System Information graphs. Can anyone guide me to the option?

**Comment by stdedos** [comment]
This is not a discussion about _any_ toggleable - but this improvement

![Image](https://github.com/user-attachments/assets/9eb4a268-82de-43c8-9b1d-a75a4d6b4e96)

**Comment by fade2gray** [comment]
@Syst3mSh0ck "One megaBIT (Mb) is equal to 1,000 bits ...". Really?
