### ISSUE TITLE
Increased CPU usage after updating to Win10 2004

### ISSUE THREAD

**Issue by Puncia** [winsiderss/systeminformer#641]
After updating Windows 10 to version 2004 (OS Build 19041.329) Process Hacker idles at a constant ~5% CPU usage, decreased to ~3% if run as Administrator.

Scrolling the main process list is also weird: I made a [short gif](https://drive.google.com/file/d/1Y71Z_xoYD-MZ-IeNecJ1jIxwUp4GyaFl/view) and as you can see every item gets duplicated and overall the scrolling does not look right. Also PH's CPU usage increases significantly as shown in [this image](https://i.imgur.com/IqUUTcd.png) taken right after recording the gif. This also applies when dragging any of the PH's windows other than scrolling. The Threads tab while doing any of these looks like [this](https://user-images.githubusercontent.com/4633311/86090315-253a3600-baaa-11ea-9bf5-1a6cb4333367.png).

Other than that, the services.exe process also idles at a constant ~5% [(image)](https://user-images.githubusercontent.com/4633311/86090504-7a764780-baaa-11ea-89b7-fd12ba872641.png), with occasional spikes, though I'm not sure how to reproduce them. [Here](https://user-images.githubusercontent.com/4633311/86090578-a0035100-baaa-11ea-988d-03fa2b6f86f2.png) is services.exe's Threads tab.

Last thing: using Task Manager [you can see](https://user-images.githubusercontent.com/4633311/86090728-ebb5fa80-baaa-11ea-88c4-9189ccd0a0a2.png) Process Hacker and services.exe are top 2 in CPU usage, BUT closing Process Hacker completely puts services.exe at a [complete rest](https://user-images.githubusercontent.com/4633311/86090892-3a639480-baab-11ea-9c3c-13be46a117e0.png)!

**Comment by dmex** [comment]
Try changing the `EnableServiceNonPoll` setting to 1

**Comment by Puncia** [comment]
That fixes the issue with services.exe, but PH still takes a lot of CPU when idling/moving windows/scrolling.

**Comment by dmex** [comment]
Can you also try disabling the "Check images for digital signatures" and "Check services for digital signatures" options in the general settings window?

**Comment by Puncia** [comment]
Sorry, I should have mentioned earlier that I already disabled both options after reading https://github.com/processhacker/processhacker/issues/595#issuecomment-610927929.

**Comment by MagicAndre1981** [comment]
you need to compile process hacker on your own to get your PDBs, start processhacker, now run cmd.exe as admin and run this:

`wpr.exe -start  CPU && timeout 30 && wpr.exe -stop C:\CPUUsage.etl`

after capturing 30s of cpu usage open the generated ETL in Analyzer (WPA.exe), [configure symbols](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/load-symbols-or-configure-symbol-paths) to use Microsoft symbol server and add an entry to your local ProcessHacker PDBs. 

Now load symbols, drag&drop the [CPU Usage (sampled)](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/cpu-analysis#cpu-usage-sampled-graph) from left side of WPA to right pane, select processhacker.exe, rightlick and filter for it. Now expand the stacks in the table and look what processhacker does.

**Comment by Puncia** [comment]
> you need to compile process hacker on your own to get your PDBs, start processhacker

well I only got so far because my own build of Process Hacker doesn't have issues. Is this normal?

**Comment by MagicAndre1981** [comment]
this is strange. Capture the trace, zip it, upload it and send the link to @dmex (look at his profile for email). He said he has the PDBs and can analyze it.

**Comment by Puncia** [comment]
I tried to build my own version again, and this time it lags. I'm not sure what went different. I tried a couple of times again, making sure it's not the official version. Sorry for the confusion.
That said, with my own laggy build I went ahead with the analysis. I know what this is doing but I don't have the experience to make guesses nor assumptions.

![image](https://user-images.githubusercontent.com/4633311/86320924-3022d100-bc38-11ea-8ea2-6844111dbd6e.png)
![image](https://user-images.githubusercontent.com/4633311/86320985-59dbf800-bc38-11ea-8fec-2585b284e6dd.png)

The "big" spikes are when I tried to use Process Hacker (like scrolling, highlighting some processes so the tooltip would pop up etc.). I don't know what the other little spikes are.

In the second screen I highlighted every single `CI.dll!SymCryptSha256AppendBlocks_ul1` function call. There's roughly ~4k as you can see, and they correspond to each spike.


Line # | Process | Stack | Count | Weight (in view) (ms) | TimeStamp (s) | % Weight
-- | -- | -- | -- | -- | -- | --
1 | ProcessHacker.exe (5448) |   | 8572 | 8.526,518000 |   | 6,95
2 |   | [Root] | 8563 | 8.517,314900 |   | 6,94
3 |   | \|- ntdll.dll!RtlUserThreadStart | 8339 | 8.292,853600 |   | 6,76
4 |   | \|    kernel32.dll!BaseThreadInitThunk | 8339 | 8.292,853600 |   | 6,76
5 |   | \|    \|- ProcessHacker.exe!__scrt_common_main_seh | 7837 | 7.795,205700 |   | 6,35
6 |   | \|    \|    ProcessHacker.exe!wWinMain | 7837 | 7.795,205700 |   | 6,35
7 |   | \|    \|    ProcessHacker.exe!PhMainMessageLoop | 7837 | 7.795,205700 |   | 6,35
8 |   | \|    \|    \|- user32.dll!GetMessageW | 7429 | 7.392,045000 |   | 6,02
9 |   | \|    \|    \|    \|- win32u.dll!NtUserGetMessage | 7428 | 7.391,045000 |   | 6,02
10 |   | \|    \|    \|    \|    \|- ntoskrnl.exe!KiSystemServiceCopyEnd | 7424 | 7.387,045000 |   | 6,02
11 |   | \|    \|    \|    \|    \|    win32k.sys!NtUserGetMessage | 7424 | 7.387,045000 |   | 6,02
12 |   | \|    \|    \|    \|    \|    win32kfull.sys!NtUserGetMessage | 7424 | 7.387,045000 |   | 6,02
13 |   | \|    \|    \|    \|    \|    \|- win32kfull.sys!xxxRealInternalGetMessage | 7422 | 7.385,045000 |   | 6,02
14 |   | \|    \|    \|    \|    \|    \|    \|- win32kfull.sys!xxxCallHook | 7308 | 7.270,842200 |   | 5,92
15 |   | \|    \|    \|    \|    \|    \|    \|    win32kfull.sys!xxxCallHook2 | 7308 | 7.270,842200 |   | 5,92
16 |   | \|    \|    \|    \|    \|    \|    \|    \|- win32kfull.sys!xxxLoadHmodIndex | 7306 | 7.268,842200 |   | 5,92
17 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|- win32kfull.sys!ClientLoadLibrary | 7301 | 7.263,810900 |   | 5,92
18 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!KeUserModeCallback | 7297 | 7.259,810900 |   | 5,92
19 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    ntdll.dll!KiUserCallbackDispatcherContinue | 7297 | 7.259,810900 |   | 5,92
20 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    user32.dll!__ClientLoadLibrary | 7297 | 7.259,810900 |   | 5,92
21 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- KernelBase.dll!LoadLibraryExW | 7286 | 7.248,810800 |   | 5,91
22 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntdll.dll!LdrLoadDll | 7282 | 7.244,810800 |   | 5,90
23 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    ntdll.dll!LdrpLoadDll | 7282 | 7.244,810800 |   | 5,90
24 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntdll.dll!LdrpLoadDllInternal | 7276 | 7.238,810400 |   | 5,90
25 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntdll.dll!LdrpProcessWork | 7263 | 7.225,724800 |   | 5,89
26 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntdll.dll!LdrpMapDllFullPath | 7262 | 7.224,724800 |   | 5,89
27 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntdll.dll!LdrpMapDllNtFileName | 7180 | 7.142,956800 |   | 5,82
28 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntdll.dll!ZwCreateSection | 7120 | 7.082,949800 |   | 5,77
29 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!KiSystemServiceCopyEnd | 7117 | 7.079,949800 |   | 5,77
30 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    ntoskrnl.exe!NtCreateSection | 7117 | 7.079,949800 |   | 5,77
31 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    ntoskrnl.exe!MiCreateSectionCommon | 7117 | 7.079,949800 |   | 5,77
32 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    ntoskrnl.exe!MiCreateSection | 7117 | 7.079,949800 |   | 5,77
33 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    ntoskrnl.exe!MiCreateImageOrDataSection | 7117 | 7.079,949800 |   | 5,77
34 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!MiShareExistingControlArea | 7110 | 7.072,921000 |   | 5,76
35 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!MiValidateExistingImage | 7108 | 7.070,897800 |   | 5,76
36 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!MiValidateSectionSigningPolicy | 7078 | 7.040,698000 |   | 5,74
37 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!MiValidateSectionCreate | 7060 | 7.022,576300 |   | 5,72
38 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- ntoskrnl.exe!SeValidateImageHeader | 6473 | 6.435,829800 |   | 5,24
39 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    CI.dll!CiValidateImageHeader | 6473 | 6.435,829800 |   | 5,24
40 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!CipValidateImageHash | 6349 | 6.311,871600 |   | 5,14
41 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    CI.dll!CipValidateFileHash | 6349 | 6.311,871600 |   | 5,14
42 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!CipCalculateImageHash | 5509 | 5.474,930700 |   | 4,46
43 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!CipImageGetImageHash | 5463 | 5.428,655900 |   | 4,42
44 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!HashpHashBytes | 5461 | 5.426,659000 |   | 4,42
45 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!SymCryptSha256Append | 3907 | 3.874,778800 |   | 3,16
46 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!SymCryptSha256AppendBlocks_ul1 | 3906 | 3.873,778800 |   | 3,16
47 |   | \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|    \|- CI.dll!SymCryptSha256AppendBlocks_ul1<itself> | 3905 | 3.872,781700 |   | 3,16

**Comment by dmex** [comment]
> looks like it is related to digital signature checking

There has been a Windows bug with checking some SHA-2 binary signatures since SHA-2 was first added to Windows a few years ago... Finding the exact binary causing the issue would be very handy so we could sent it to Microsoft and get the issue fixed.

> In the second screen I highlighted every single CI.dll!SymCryptSha256AppendBlocks_ul1 function call

Your stack trace is showing an application trying to inject a binary into Process Hacker using either the SetWindowsHookEx function  and/or AppInitDlls registry keys but we're using the Windows extension point mitigation policy which disables both of those injection methods for the current process. Process Hacker also uses the Windows signed only mitigation policy which prevents loading/injecting binaries not signed by Microsoft.

lines 14-21 on your stack trace here:

![image](https://user-images.githubusercontent.com/1306177/86333841-cafaca00-bc8f-11ea-86ad-8d2cbd890f62.png)

The injection would be returning an error code and the calling process is likely immediately trying to inject the binary again and again which is causing the random CPU usage usages you've been seeing.

Try closing/terminating all other programs on your machine until the CPU usage issue disappears and it'll probably be the application causing the issue. If that doesn't work there are some tools available for checking which applications have registered these hooks.

**Comment by Puncia** [comment]
Easier than I thought, the culprit is Overwolf. Closing it makes everything go back to normal.
I suppose it would be worth to contact their support so they can handle this specific case better.

Either way thanks for your help.

**Comment by dmex** [comment]
> the culprit is Overwolf.

Win10-2004 added an undocumented override exemption to the ProcessExtensionPointDisablePolicy security mitigation which was previously used to disable unauthorised third party window hooks being added to Chrome, Edge, Process Hacker and other software using this mitigation but these new override exemptions now defeat the entire purpose of using that mitigation on Win10-2004 and above.

The major performance issues with Process Hacker are a direct result of these changes. We also use the MicrosoftSignedOnly security mitigation to prevent loading of non-Microsoft binaries but win32k.sys is using the newly added exception to the ProcessExtensionPoint mitigation policy in an attempt to inject window hook DLLs from third party software into Process Hacker which then faults due to our binary also using the MicrosoftSignedOnly mitigation policy which triggers an infinite loop within win32k.sys and the kernel executive.

1) win32k.sys overrides the ProcessExtensionPoint security mitigation (newly added backdoor exemption for UIAccess=true).
2) win32k.sys queues an APC into Process Hacker for injecting the window hook DLL with LoadLibraryExW
3) LoadLibraryExW returns an error while loading the injected DLL due to the MicrosoftSignedOnly security mitigation.
4) win32k.sys ignores the failure and repeats the entire procedure over and over again in an infinite loop.

The APCs queued to Process Hacker by win32k.sys are handled internally by the GetMessage (NtUserGetMessage) function and cause the process to utilize 100% of a single processor core (you'll see 50% of a dual core machine, 25% of a quad core etc...) due LoadLibraryExW being executed by these APC requests within our process thousands of times every second.

I've tried raising the issue with Microsoft but have not received a response yet.

**Comment by dmex** [comment]
I've disabled mitigation polices for users running Win10-20H1 and above since Microsoft still hasn't fixed the crippling performance issues: https://github.com/processhacker/processhacker/commit/edf229a3e9e54490f231366e2e460d647e07b805

It's extremely sad that some random process on the machine calling SetWindowsHookEx can make Process Hacker completely  unusable because of that stupid backdoor policy bypass Microsoft added for UIAccess. 🤮

The only other way to fix the issue - without disabling security like commit edf229a - would be splitting the project into pieces and launching those parts on a separate desktops since window hook DLL injection using SetWindowsHookEx doesn't work across desktop sessions.... That will take quite some time to implement so unless Microsoft fixes these issues the security mitigations will now remain disabled. 😕

You can also expect attackers will now exploit those changes (great). So I've updated the policy descriptions when viewing the process mitigations so that you're (at least) aware of those changes (since they're not documented anywhere yet): https://github.com/processhacker/processhacker/commit/e856774d8e4583d46f478f56537cfc2d7bc684d0

😕

**Comment by ImSpecial** [comment]
So is this also the cause for all the Event View Error spam that generates when using Process Hacker? For example "Applications and Services Logs" > "Microsoft" > "Windows" > "CodeIntegrity"

**Comment by dmex** [comment]
> all the Event View Error spam

Yes. The events are generated by LoadLibraryEx when the injected window hook DLL failed to load because of the MicrosoftSignedOnly policy. The window hook injection is stuck in an infinite loop so you'll get an infinite amount of log messages 😂

**Comment by ImSpecial** [comment]
That sucks, but good to know where and why they come from. By chance I've noticed "Kernel-EventTracing" Errors as well, and they seem to pop up (at least more often) while using Process Hacker, do you know if PH is also a cause? I cannot tell honestly, it might just be coincidence too.

**Comment by dmex** [comment]
> I've noticed "Kernel-EventTracing" Errors as well, and they seem to pop up (at least more often) while using Process Hacker

The error code should be when the name already exists.

**Comment by MagicAndre1981** [comment]
I just learned that applications with UIAccess=true need to be in program files or windows to run correctly. 

How do you run the app that triggers it? From such system folders or from a different location?

**Comment by dmex** [comment]
> How do you run the app that triggers it?

You can just install a third party application to easily demonstrate the issue.

Download Overwolf from here:
 https://www.overwolf.com/
https://download.overwolf.com/install/Download?Channel=web_dl_btn2

1) Install Overwolf and then execute it. 
2) Start Process Hacker.

You will see thousands of events in the event log caused by the infinate loop in the kernel and if you're running sysinternals debugview you'll see thousands of debug messages related to DLL injection failing because of the security policy.

You can also view the threads of Process Hacker while this is happening and see user32_ClientLoadLibrary being called and generating 100% utilization on some machines loading/unloading DLLs thousands of times a second and moving the mouse over Process Hacker windows or doing anything that generates a window message causes user32_ClientLoadLibrary to be called 10x more often than normal causing even more performance issues.

I've been forced to disable Windows mitigation policies by default because the performance impact of this issue on some machines is insane and Microsoft has so far refused to fix the issue. So you will now have to manually enable the Windows mitigation policies by selecting the 'Enable mitigation policies' from the Process Hacker options window:
![image](https://user-images.githubusercontent.com/1306177/102692643-cbe8dd80-4268-11eb-8342-0d40992bd0a6.png)

**Comment by realyukii** [comment]
> If that doesn't work there are some tools available for checking which applications have registered these hooks.

Hi @dmex 
may I know what the tool is? [I'm wondering if there's some alternative to HookTools](https://github.com/winsiderss/systeminformer/issues/1947)
