### ISSUE TITLE
devenv, msedge, discord, skype and other processes cannot be suspended

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#856]
NtSuspendProcess will no longer allow suspension (regardless of privilege level) of some processes including:

Visual Studio (devenv.exe)
Microsoft Edge (msedge.exe)
Skype (skype.exe)
Discord (discord.exe)
Steam (steamwebhelper.exe)

Windows 8.1 and Windows 10 are both affected. The issue appears related to process threads that are calling NtFsControlFile and NtReadFile on synchronous pipe handles when attempting to suspend the thread.

**Comment by MagicAndre1981** [comment]
I tested it in Win10 1909 VM and here I can suspend/resume devenv.exe. So maybe defender releated? I use NOD32

**Comment by dmex** [comment]
> So maybe defender releated?

I don't have 'security' software installed...

> I tested it in Win10 1909 VM

I've been able to reproduce the issue on all versions of Windows 10 provided the application uses named pipes and has threads in the Executive wait state calling NtFsControlFile (ConnectNamedPipe) and NtReadFile (ReadFile)

For example when attempting to suspend Google Chrome (chrome.exe) processes... One of those processes won't actually suspend leaving two threads deadlocked in the kernel:

![image](https://user-images.githubusercontent.com/1306177/113504348-e1191c00-957a-11eb-8687-cc9c21af106e.png)

**Comment by diversenok** [comment]
Oh, I see, I also thought I could not reproduce it, but I know this behavior; it's been here for a while.

I remember it in the case of cmd. As you said, on Windows 10, its main thread waits for input in the Wait:Executive state (as opposed to Wait:WrLpcReply on Windows 7). Suspending **doesn't** transfer it to the Wait:Suspended state until wait completion but **does** prevent user-mode code from executing.

So, I won't say that suspending is entirely broken. After all, it still achieves its primary goal. However, it also does not indicate the wait reason currently in the process snapshot. You can still query a suspend count as a workaround; though, it does not scale up well.

**Comment by diversenok** [comment]
Okay, I think I have a reasonably scalable heuristic workaround:

1. When viewing the list of threads for a process, check the suspend count for each thread in the Executive state. If the value is non-zero, mark it as suspended.

2. When viewing the list of processes, check if a process has any threads in states other than Executive or Suspended. If it doesn't, check the suspend count for each Executive thread. This algorithm will skip most of the processes, so the total impact on performance should not be that bad.

**Comment by dmex** [comment]
> I think I have a reasonably scalable heuristic workaround

The problem is when you're trying to debug your own software and your threads are not getting suspended and PH is showing them suspended -  you're going to be very confused as to what the issue is.

It's likely there are more than a few applications since 2000 that are now faulty because of this issue and the SuspendThread function. Showing those threads with the current (buggy) non-suspended state would indicate a problem with Windows rather than the application itself. Right now we're showing exactly what Process Explorer, Task Manager and Resmon are showing which is the correct behaviour and if you're trying to figure out why some application is now broken you'll see the same result in PH as your own software does?

**Comment by diversenok** [comment]
There can be two different definitions for a suspended thread:

1. A thread that has KWAIT_REASON::Suspended
2. A thread with a non-zero suspend count

At the times of Windows 7, these definitions seemed equivalent; but on Windows 10, they are not because of this behavior. All the tools you mentioned rely on the first definition; I suggest switching to the second one.

If we don't go into technical details, what is the primary goal of suspending a thread? To prevent it from running user-mode code. What does calling SuspendThread and debugging do? They queue a Kernel APC that prevents the system from switching the thread into user mode. In this sense, they both behave correctly, regardless of whether they set KWAIT_REASON::Suspended or not. If you have any examples of when a thread can continue executing user-mode code after applying SuspendThread to it or not acknowledging events from the process's debug port, please share them.

While having KWAIT_REASON::Suspended means a non-zero suspend count, observing other states does not necessarily imply a zero value for it. Therefore, checking the suspend count seems like a better indicator.

Finally, even on Windows 7, SuspendThread does not always transition a thread into KWAIT_REASON::Suspended. One example of it is debugging. When the system waits for a debugger to acknowledge a debug event, the target thread appears with KWAIT_REASON::Executive with the suspend count of one. Calling SuspendThread, in this case, increments the suspend count but does not change the state until the debugger finally responds. ResumeThread decrements it, but never below one.

I think SuspendThread behaves somewhat correctly. While it must freeze user-mode code, it does not guarantee to switch the thread into KWAIT_REASON::Suspended. Did it ever? Windows 10 made this behavior more obvious, but I don't think it broke anything except for the tools that use this state to identify suspended threads or processes. That's why I suggest switching to a different definition: it describes what happens more precisely.

**Comment by dmex** [comment]
@diversenok 

> If you have any examples of when a thread can continue executing user-mode code after applying SuspendThread to it or not acknowledging events from the process's debug port, please share them.

I found threads that continue executing in usermode after calling SuspendThread... The NT thread pool with state WrQueue created by ExpWorkerFactoryCreateThread.

Note the start address ntdll.TppWorkerThread, state WrQueue and the Created time of these threads:
https://i.imgur.com/cAexcMX.png
https://i.imgur.com/KaqTkkz.png
https://i.imgur.com/KaqTkkz.png
https://i.imgur.com/j6haFvN.png
https://i.imgur.com/gMlIVMz.png

The call stack for NtCreateThreadEx:
https://i.imgur.com/chQ3Zfw.png

They generally won't suspend and if they do get suspended ExpWorkerFactoryCreateThread will just create another thread in the process ignoring the suspension and continue executing usermode code.

**Comment by dmex** [comment]
@diversenok 

NtCreateProcessStateChange on Windows 11 which was supposed to fix these issues is also broken.

**Comment by diversenok** [comment]
@dmex

Well, I guess I agree; although, it still kind of depends on the meaning you put into it.

The process **does get frozen** as per `PROCESS_EXTENDED_BASIC_INFORMATION`, even though some threads might not change their wait reason to WrSuspended. I don't see a big problem here, except for the tools that rely on the wait reason instead of the suspend count to determine suspension.

On the other hand, `NtCreateProcessStateChange` relies on regular freezing and not deep freezing used by jobs, so threads created with `THREAD_CREATE_FLAGS_BYPASS_PROCESS_FREEZE` can still escape it. But I must admit that the implementation improved considerably over time. The early versions of this function from Insider builds used plain old suspension (with its inherent race conditions); plus, regular freezing was less reliable in general because all new threads were bypassing it by default. So, `NtCreateProcessStateChange` is way less broken than `NtSuspendProcess` is, provided that your goal is to prevent code execution.

**Comment by dmex** [comment]
Closing as completed with Windows 11 Freeze support

**Comment by isaak654** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/3375
