### ISSUE TITLE
A major delay in displaying status-bar fields 

### ISSUE THREAD

**Issue by Yaron10** [winsiderss/systeminformer#929]
**Describe the bug**
The status-bar fields take ~4 seconds to display (compared to ~1 second in v2.39).

**To Reproduce**
1. Run the latest Nightly.
2. Note the status bar fields.
3. A major delay in displaying the status-bar fields.

**Expected behavior**
The the status-bar fields and values should be displayed much faster.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]

Thank you for your great work.

**Comment by dmex** [comment]
The delay is intentional as some of the other new statusbar values depend on data that gets sampled over a time period and those samples don't exist when first launching the application.

You should probably use a lower interval update of .5s so the data gets populated more quickly otherwise leave the application running in the system tray.

**Comment by Yaron10** [comment]
> The delay is intentional as some of the other new statusbar values depend on data that gets sampled over a time period and those samples don't exist when first launching the application.

1. I assume this is new in the latest versions, correct? (As I've mentioned, in v2.39 the delay is minimal).
2. I'm only using `Processes`, `CPU Usage`, `Selected` and `Selected WS`. - Is the delay necessary for those fields?

>  You should probably use a lower interval update of .5s

This helped to some extent.

Thank you. I appreciate it.

**Comment by Yaron10** [comment]
@dmex,

Thank you your great ongoing work. 👍 
Where can I download the binary containing https://github.com/winsiderss/systeminformer/commit/e49e3e25d5eba6bc2319fd3d7024e5919dd2894d?

**Comment by dmex** [comment]
Builds are on hold until the migration is completed 👍

**Comment by Yaron10** [comment]
👍 
Thanks again and best of luck.

**Comment by Yaron10** [comment]
@dmex,

I've installed v3.0.5578 and I don't see any improvement. The delay is still quite significant. 

Thank you.

**Comment by dmex** [comment]
> The delay is still quite significant.

The delay is 3 seconds? All previous versions of the application were using a delay of 2 and changing the value to 3 was intentional to improve startup performance.

> I don't see any improvement.

You need to provide a usecase/explain the reason why you need the statusbar displayed within the first 3 seconds of starting the application.

Is the statusbar the only part of the application you're using or are you only complaining that it's delayed?

**Comment by Yaron10** [comment]
@dmex,

Thank you. I appreciate it.
I'll try it when the binary is available.

**Comment by dmex** [comment]
@Yaron10 

Latest nightly now includes the changes. You can change the delay by modifying the `ProcessHacker.ToolStatus.DelayConfig` setting higher/lower. For example a value of 0 or 1 will instantly initialize the statusbar after startup while a value of 5 will delay initialization for 5 intervals.

**Comment by Yaron10** [comment]
@dmex,

👍 
Excellent!
I'd like to thank you again for your great work. Prolific and _good_ developers as yourself are quite rare.

Happy Holidays!
