### ISSUE TITLE
ProcessHacker wont launch

### ISSUE THREAD

**Issue by NumbuhUno** [winsiderss/systeminformer#964]
I have downloaded PH on  WJ32, but when I launch it it says "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item." I have tried giving the setup permissions but even when i gave it, it would say the same thing

**Comment by iam-py-test** [comment]
> > is there any way to unblock it or no?
> 
> You would have to find whatever setting webroot uses to block you on your own machine? You could always uninstall them and switch to a better product like malwarebytes.

Nope, even Malwarebytes detects this: https://forums.malwarebytes.com/topic/281338-process-hacker-239-false-positive/#comment-1490639

**Comment by dmex** [comment]
> Nope, even Malwarebytes detects 

They told me they didn't consider PH an issue just a few months ago: https://forums.malwarebytes.com/topic/270437-process-hacker-303813-false-positive/?do=findComment&comment=1446677

???

> It becomes rather obvious to most users that something posted three years ago is highly unlikely to be relevant today

It's still relevant. If you're going to publish a blog post claiming you don't consider it an issue, at least publish one stating why it's now an issue otherwise you're making yourselves look incompetent.

> Just because something perfectly legit is being abused by malware doesn't mean it should be outright blocked (and deleted)

No they shouldn't - Blocking and deleting our binaries is what malware and spyware does - they should be working with us to prevent attacks rather than becoming malware themselves and copying what malware does.

I've never seen any binary samples or technical information showing Process Hacker being abused by malware and ransomware - I've seen it claimed but nobody has ever published samples or code showing these attacks... What benefit is there in keeping this information secret? If you're already blocking our binaries, then why continue keeping samples of these attacks using our code a secret? 

All that does is prevent us from fixing a security issue, allowing attacks to continue, while you to continue blocking our binaries forever because we'll never be know about these issues and fix whatever issue because you're keeping it a secret to justify blocking our binaries... 

> How is 'Process hacker' more dangerous then Sysinternals's Process Explorer, or Task Manager, or any of the other hundreds of other process management tools out there?

Process Explorer has the exact same features as Process Hacker including the exact same termination feature. There's even exploit code for Process Explorer (https://github.com/Yaxser/Backstab) but where's the exploit code for PH?

**Comment by iam-py-test** [comment]
> 



> > Nope, even Malwarebytes detects
> 
> They told me they didn't consider PH an issue just a few months ago: https://forums.malwarebytes.com/topic/270437-process-hacker-303813-false-positive/?do=findComment&comment=1446677
> 
> ???
> 
> > It becomes rather obvious to most users that something posted three years ago is highly unlikely to be relevant today
> 
> It's still relevant. If you're going to publish a blog post claiming you don't consider it an issue, at least publish one stating why it's now an issue otherwise you're making yourselves look incompetent.
> 
> > Just because something perfectly legit is being abused by malware doesn't mean it should be outright blocked (and deleted)
> 
> No they shouldn't - Blocking and deleting our binaries is what malware and spyware does - they should be working with us to prevent attacks rather than becoming malware themselves and copying what malware does.
> 
> I've never seen any binary samples or technical information showing Process Hacker being abused by malware and ransomware - I've seen it claimed but nobody has ever published samples or code showing these attacks... What benefit is there in keeping this information secret? If you're already blocking our binaries, then why continue keeping samples of these attacks using our code a secret?
> 
> All that does is prevent us from fixing a security issue, allowing attacks to continue, while you to continue blocking our binaries forever because we'll never be know about these issues and fix whatever issue because you're keeping it a secret to justify blocking our binaries...
> 
> > How is 'Process hacker' more dangerous then Sysinternals's Process Explorer, or Task Manager, or any of the other hundreds of other process management tools out there?
> 
> Process Explorer has the exact same features as Process Hacker including the exact same termination feature. There's even exploit code for Process Explorer (https://github.com/Yaxser/Backstab) but where's the exploit code for PH?

Agreed. I used both Process Hacker and Process Explorer and really, (in my opinion) the only really major feature which is Process Hacker-only is the notifications. Besides, PH is open source and I don't think PE is 
By the way, sp123 is me
