### ISSUE TITLE
is there a possibility to change the name from processhacker e.g. to process checker?

### ISSUE THREAD

**Issue by matuskox** [winsiderss/systeminformer#978]

**Comment by ImSpecial** [comment]
Why? In an attempt to try and fool AV/false positives...?

Might as well call it "BirthdayCakeHappyFunTime" then.

**Comment by cubakcabak** [comment]
i think **ProcessManager** is more suitable name, if developer decide to rename it.

**Comment by spytheman** [comment]
I like the name `processhacker`.

**Comment by benrg** [comment]
I favor changing it, not because I dislike the name, but because I suspect that it would significantly reduce the frequency of issues like #904 and #997, which are real usability problems. Maybe I'm just being cynical, and the vendors always thoroughly investigate Process Hacker before they unaccountably decide that it's malware.

**Comment by microdee** [comment]
> I like the name `processhacker`.

we all do. Evil MegaCorp™ Inc. doesn't. It has Hacker in the name. That's not stonks!

**Comment by valinet** [comment]
Where’s the “free speech defending army” in this case? Oh yeah, excuse me, this is a legit case, not some politically motivated bullshit, so they don’t bother “educating” the public opinion in this case.

Thumbs up for the developer, besides appreciating the usefulness and the amount of work required for such an app, it’s also a tremendous fight with Microsoft and AV vendors just for the privilege (nowadays) to be able to run a legitimate application freely, as requested by the computer’s user.

Thank you🙏

**Comment by Masamune3210** [comment]
The stigma around the word hacker is reallllllly dumb, the fact that most people and companies see it and immediately assume the worst is possibly the stupidest thing ever

**Comment by microdee** [comment]
or go on the gnu/unix style naming like `proch` (in the spirit of `htop`)

**Comment by SanderBouwhuis** [comment]
I too have to say I'm having a hard time recommending this to be installed on other people's computers. I have some customers I help on a regular basis who could really use process hacker because it has more features than the windows task manager. But, because of the name it is a real hurdle.

Please, please, change the name. Remove the word hacker. Some of the suggestions already mentioned above are really good : ProcessManager and ProccesHandler and ProcessInspector.

Words matter!

**Comment by Masamune3210** [comment]
They really dont, not when the only reason to change the name is a decades outdated stigma against the word in question. Changing a name just because people don't like the name is missing the point

**Comment by valinet** [comment]
Yeah, and it’s not that they don’t like it even, it’s because some people think something named “hacker” is a clear indication something’s malicious, and similarly some sell “highly praised” antivirus solutions whose top detection methods revolve around checking whether the executable name contains words like these. I wouldn’t change the name for anything in the world; not only is this software a very good program for its purpose, but it can also be used as a very efficient stupidity detector - a quick way to asses how smart a person is without asking too much from them.

**Comment by microdee** [comment]
> decades outdated stigma against the word in question

everyone loves the name Process Hacker, I also do, and it would be a better word if this name wouldn't matter. But unfortunately the source of this problem (as usually with other problems in the world) corporate culture. Notice how none of the corporate targeted software tools contain "Hack" or "Crack" or any 1337 scene stuff in their name, because it raises suspicion for all the wrong reasons. Corporate shit needs to be non-threatening, sterile, radio-friendly, unimaginative and should not invoke any emotion other than optionally awe and/or optimism. It's horrible, I despise that, but unfortunately they will ban anything which goes against those.

Because of these shenanigans ProcessHacker with its name is only useful on personal PC's which the user has full control over, but painfully it can't be used in many professional or academic environments, and again because our prejudicial society is broken, this amazing tool cannot reach its full potential and reputation it can possibly have. Unfortunately for a rightfully paranoiac IT security person or sysadmin who don't know this tool and doesn't have time to look into this tool, the name might unjustly automatically suggest malicious intent. :(

**Comment by InternetPseudonym** [comment]
>Corporate shit needs to be non-threatening, sterile, radio-friendly, unimaginative and should not invoke any emotion other than optionally awe and/or optimism. It's horrible, I despise that, but unfortunately they will ban anything which goes against those.

THIS!

I also love the name - but i also want to use it everywhere with absolutely no problem. This tools deserves a permanent place on every developers' shelf ... but that won't be possible with "hacker" in its name. We are always forced to either go against corporate policy or convince a lot of difficult-to-deal-with people

**Comment by InternetPseudonym** [comment]
search&replace rarely works in projects which grew beyond a certain scale. Process Hacker pretty much grew into a behemoth so failure of that action should be guaranteed ... but it's worth a try i guess

**Comment by PleasantMachine9** [comment]
> What if you just build it yourself under another name? I guess it's trivial to mass-find-and-replace Hacker with Manager.

FYI: even if this *were* trivial (which it isn't really, let's be honest), it would be requiring you to buy your own digital code signing certificate and signing all the binaries (kernel driver as well maybe?) yourself. Those certificates are hundreds of dollars and a huge hassle all around.

The alternative, which is getting unsigned executables past IT and AV is not much easier, if not harder than getting something through with "hacker" in its name.

**Comment by SeriousM** [comment]
That would mean that someone would have to donate a few hundred dollars if
the "hacker" part should be changed... I guess that will never happen, ppl
expect open source to be free but in reality it isn't.

**Comment by dmex** [comment]
The project name has changed 🥳

**Comment by lynrayy** [comment]
How to change name in processhacker? I need it because virus closing my task manager and processhacker by window name!!!!!!!!!!!!

**Comment by SanderBouwhuis** [comment]
@lynrayy 
You can download SystemInformer.
1. It is the new name of the ProcessHacker.
2. It is where all new developments take place.

**Comment by lynrayy** [comment]
Do you think the virus developers are standing still and won't add a new name to the list of keywords for closing windows? The idea is that the program would have something in the window title that you specify yourself, and not the original name that the virus detects

**Comment by SanderBouwhuis** [comment]
Actually, I think virus developers are stupid and only added ProcessHacker because of the name. SystemInformer IS NOT A VIRUS. Any virus developer would know that.
The alternative option is that the virus scanner simply looks at what SystemInformer can do, and on the basis of that block it because of heuristically determining that either the behaviour is suspicious, or simply that SystemInformer is a 'potentially unwanted program'.

But, again... there is NO virus in SystemInformer.
