### ISSUE TITLE
Feature request: Dark theme

### ISSUE THREAD

**Issue by AndreyAkinshin** [winsiderss/systeminformer#98]

**Comment by dmex** [comment]
The theme-fixes branch has a dark theme but it's too early (and unstable) to use yet.

**Comment by timofonic** [comment]
@dmex Please comment us when it's ready!

**Comment by AndreyAkinshin** [comment]
@dmex, any progress?

**Comment by dmex** [comment]
@AndreyAkinshin 

The latest nightly includes a checkbox on the general options tab for enabling theme support. You can change the Graphs > 'use old colours' option at runtime for a light/dark theme.

Theme feedback and suggestions welcome 😄

**Comment by AndreyAkinshin** [comment]
@dmex, awesome, thanks!

The System Information looks much better now. However, on my 4K monitor, the "System" and "CPU" labels look strange:

![image](https://user-images.githubusercontent.com/2259237/43188917-020d7c38-8ffe-11e8-8827-aeaf086c015e.png)

The "Options" page looks too contrast because of the "pure" white font color. It makes sense to find better text colors (e.g., around #A9B7C6):

![image](https://user-images.githubusercontent.com/2259237/43189115-85d7064c-8ffe-11e8-9ec7-4befdb066329.png)

Many windows have partial dark theme support. E.g., "Find Handles or DLLs" looks like this:

![image](https://user-images.githubusercontent.com/2259237/43189176-a659b518-8ffe-11e8-8b36-9012517f646d.png)

The main "Processes" tab doesn't support the dark theme at all.

Anyway, thanks for the initial support. Looking forward to trying the updates.

**Comment by dmex** [comment]
> However, on my 4K monitor, the "System" and "CPU" labels look strange

I've reported the issue to Microsoft since it's a recent issue with Windows 10:

Win8:
![image](https://i.imgur.com/A6LaOPK.png)

Win10-RS3:
![image](https://i.imgur.com/W650Qpa.png)

DrawTextW on Windows 7 and Windows 8 both draw the text correctly but Windows 10... 🤔

> The "Options" page looks too contrast because of the "pure" white font color. It makes sense to find better text colors (e.g., around #A9B7C6):

The padding/spacing between the text needs to be increased when using "pure" white colors but it's proving to be a problem with some controls. I think adding an options page for changing the theme colors and settings might be better?

> Many windows have partial dark theme support. 

Scrollbars and some other dialogs don't support dark themes. Microsoft fixed those issues on the next version of Windows 10 (releasing sometime next month or October) 👍

**Comment by yossizahn** [comment]
Hi, 
The "Show details for all processes" button should be desaturated when PH is running elevated. This doesn't happen when theme support is enabled.
![image](https://user-images.githubusercontent.com/19174667/47431096-ce903b00-d7a3-11e8-8501-749c547b9721.png)

**Comment by ferenczy** [comment]
So how is it supposed to work? I have to _Enable theme support_ on the _General_ tab under the _Options_ first, restart the application, enable _Show advanced options_ on the same tab and then I can change individual colors on the _Advanced_ tab? There are no themes yet (I mean sets of predefined colors), right?

Also, toolbar buttons are displayed without any icons when the theme support is enabled. Moreover, _Find window_, _Find window and thread_, _Find window and kill_ and _Show details for all processes_ also don't have any text so there's just an empty space:

![image](https://user-images.githubusercontent.com/1712992/49528295-fe0e8900-f8b3-11e8-8148-e94d8db9d1d9.png)

Doesn't matter if I have default or modern icons, but in the _Customize..._ dialog, they have proper icons.

**Comment by dmex** [comment]
> There are no themes yet (I mean sets of predefined colors), right?

You can toggle the dark mode by selecting the 'use old colours' option on the Options > Graphs window.

> toolbar buttons are displayed without any icons when the theme support is enabled

It's a known issue that I haven't been able to find and fix yet 😢

**Comment by Aidolii** [comment]
@ferenczy You have to enable 'Use old colors' in the Graphs section, this makes the entire application have a dark theme. I guess it's like a hidden option for testing purposes?

**Comment by KaKi87** [comment]
Hey there, what's the status here ? :)

**Comment by dmex** [comment]
@KaKi87 

The nightly builds support dark themes when you select the "Enable theme support" checkbox on the options window 👍 
https://wj32.org/processhacker/nightly.php

**Comment by KaKi87** [comment]
Thanks !
When will 3.0 be stable ?

**Comment by dmex** [comment]
@KaKi87 

3.0 is stable if you consider the standard set by Windows 10 😄

**Comment by KaKi87** [comment]
Nice ! Well, I'm using skip ahead builds on my daily use computer and I find it more stable than the stable release channel lol 😂 So, it seems nice, thanks !
But it was still a serious question xD

**Comment by dmex** [comment]
> But it was still a serious question xD

It was a serious answer. The development standard for Windows 10 is the same standard for the nightly builds of Process Hacker.

Microsoft developers push all Windows changes to a git repository which are compiled nightly on Azure and these builds are pushed to the "preview ring" before they're later "released" to the public  (Microsoft has discussed this process a few times).

We push changes to our github repository which are compiled (semi) nightly on Appveyor (hosted by Azure) and these builds are pushed to the "nightly" branch and made available to everyone using 3.0 builds.

The biggest difference between the two is that when issues are reported to our project issue tracker we can make the changes available to everyone in less than five minutes (the time appveyor takes to compile the nightly builds) meaning if there is an security issue or a faulty commit it can and does generally get reverted and/or fixed in less than five minutes.

This process is more visible on Github since everything is public (Windows Calculator and .NET Core are also hosted on Github) and we're following the same standard. The ability to make changes available in minutes compared to months makes things easier and generally more accepted by users these days than previously since things can be changed and fixed quickly.

There will be a new "stable" release soon for the LTS - Long Term Support - version which is just a version of the nightly build that doesn't have any reported issues.

**Comment by KaKi87** [comment]
I understand, but even when all issues are fixed, what makes a release stable is the fact that it has been fully tested before released, not a nightly.

**Comment by onliner2021** [comment]
Is there any way to change the bright background colors?
In settings there are all sorts of colors one can change, but not the bright ones.
My Windows is running in "dark" mode, but I have not changed it to high contrast mode, as that puts rectangles everywhere...
And I also would like to avoid changing the Windows default colors with something like...
https://www.wintools.info/index.php/classic-color-panel
...as there are more than enough programs out there, that have very poor support for changed windows default colors...

It would be great if Process Hacker could provide support for changing the background and font colors so that one can have a true dark mode - totally independent of what the windows settings might be.

Thanks for considering.

**Comment by adamency** [comment]
Is this feature still not stable enough to be included in the stable release ?

**Comment by moonspeak** [comment]
Is there any support for automatic theme switching? I use AutoDarkMode to switch Windows between light and dark based on the time of day, which is amazing for visibility. It seems this theme implementation simply changes the app colors until the feature is disabled. Is there any way to make it follow the system theme or any plans to do so? That would be amazing.

**Comment by GlassWolfLH** [comment]
This issue has been requested since 2018.7 years later and no resolution?  Can we get a dark mode, or system mode reflected in this app at long last, please?  Some of us with visual impairment require dark mode for an app to be viewable.
Regards.

**Comment by jay1891** [comment]
It is available as experimental.

<img width="1106" height="438" alt="Image" src="https://github.com/user-attachments/assets/2eb39e19-ae1f-4fda-974c-3ee645d276e8" />
